### ISSUE TITLE
Option to hide toolbar is not present

### ISSUE THREAD

**Issue by adotg** [YACReader/yacreader#104]
OS: MacOS Mojave 10.14.5
YacReader version: 9.6.2

Option to hide toolbar is not present resulting in an always present toolbar hampering the experience of reading.

![image](https://user-images.githubusercontent.com/7579500/69661737-f2aa0400-10a8-11ea-888a-05290fd631d1.png)

**Comment by selmf** [comment]
There is not option, but there is a keyboard shortcut. Press "h" to hide, press "h" again to unhide.

**Comment by adotg** [comment]
Super. Closing this.
