### ISSUE TITLE
Support 7z through unarr.

### ISSUE THREAD

**Issue by crocket** [YACReader/yacreader#113]
unarr supports 7z now.

**Comment by selmf** [comment]
Hi,

as the current maintainer of the unarr code I am well aware of its 7z support capabilities and while the git version does support easy inclusion of 7z, the performance isn't as fast as I'd like it to be. I will reenable 7z support using unarr once version 1.1.0 is released. If you'd like to have this support sooner, you are more than welcome to provide a PR. This is very easy - all you need to do is:

1. uncomment the line containing ar_open_7z_archive in compressed_archive/unarr/compressed_archive.cpp
2. add .7z and .cb7 to the unarr supported file extensions in common/comic.cpp

Happy hacking, and … please use a less demanding communication style when describing issues. As much as I like short and precise descriptions, we're humans, not bots, and a minimum of politeness goes a long way.

**Comment by crocket** [comment]
>  please use a less demanding communication style when describing issues.

Understandable.

**Comment by jeremydouglass** [comment]
@selmf -- thank you for this response, and for your all your maintenance and support effort.

Would you like the PR that you describe on master, or on develop?

**Comment by selmf** [comment]
Either develop or both, but @luisangelsm will prefer develop. The change is non-intrusive and will not cause any breakage when an older version of unarr is being used. You still need to enable 7z support when building unarr for it to work - the description on how to do this is on the github page ;)

**Comment by jeremydouglass** [comment]
> add .7z and .cb7 to the unarr supported file extensions in common/comic.cpp

If I'm understanding right, looks like this second change is already in place in develop:

https://github.com/YACReader/yacreader/blob/0b837647341c6b858f404254c5a8621962048a09/common/comic.cpp#L43-L52

**Comment by selmf** [comment]
No, this is for builds that don't use unarr. You need to add .7z and .cb7 to the #else branch below.

**Comment by jeremydouglass** [comment]
Okay, will do.
