### ISSUE TITLE
Linx: Hidpi is ignored, icons are miniscule, dialogs unusable. 

### ISSUE THREAD

**Issue by EricGebhart** [YACReader/yacreader#127]
Running today's version of arch linux and yacreader. 
This possibly two problems.  Obviously xft:dpi setting is being ignored. Icons and fonts are so tiny I need a magnifying glass. The menus are the same. 

The other problem that manifests is that the dialogs are so narrow they are useless. The exit button doesn't even show.  The font sizes seem reasonable but not great.

It is impossible to change any settings for yacreader because the values don't show. 

My dpi is set to 196 in Xresources.

**Comment by selmf** [comment]
We support hidpi, but the implementation we have was more or less written for Mac OS X and retina displays - years ago. Our assets are not quite up to the job of variable scaling factors yet.

There is also the problem that hidpi support with the Qt toolkit/framework is still a work in progress. Did you enable hidpi support for Qt5 apps as [instructed](https://wiki.archlinux.org/index.php/HiDPI#Qt_5) on the arch wiki?

**Comment by EricGebhart** [comment]
Ah, thank you. That works. I don't actually use kde or gnome, or xfce, so I didn't realize that there were more settings needed.  My xfce panel, that  I do use, responded nicely to the xresources setting. 

The worst part is that any apps that use those toolkits are stuck with these odd behaviors. Identifying the toolkit in use by looking at source code to then do the appropriate fix is a bit unfriendly of the system. Thankfully Arch does have great docs.  I suppose it is wise to just implement all the settings.

**Comment by selmf** [comment]
You're welcome. I don't have a hidpi display, so if you notice anything strange or quirky, feel free to open another issue so we can take it into account when we work on hidpi stuff again ;)

**Comment by EricGebhart** [comment]
The dialogs have been problematic, but I need to verify and test some. It maybe better now. Inkscape has some weird things too.  I think it is qt based.
