### ISSUE TITLE
YACLibrary Qt Exception

### ISSUE THREAD

**Issue by Praxidice** [YACReader/yacreader#133]
Hello,
I'm using YAC Library running in the background as a tray icon on Windows 10. After about 12 hours or so of sitting in the tray I always get the following exception:

> Faulting application name: YACReaderLibrary.exe, version: 0.0.0.0, time stamp: 0x5d8f1ac4
Faulting module name: qwindows.dll, version: 5.12.4.0, time stamp: 0x5d01c6b4
Exception code: 0xc000041d
Fault offset: 0x0000000000003544
Faulting application path: C:\Program Files\YACReader\YACReaderLibrary.exe
Faulting module path: C:\Program Files\YACReader\platforms\qwindows.dll

0xc000041d is STATUS_FATAL_USER_CALLBACK_EXCEPTION: An unhandled exception was encountered during a user callback.

I guess a Qt callback is throwing an exception. I won't have time to really debug it for a week or two, but I still wanted to bring it up here.

**Comment by luisangelsm** [comment]
Hi,

thanks for reporting the problem, I also have YACReaderLibrary in the tray
running in Windows 10 but I never had a single crash, so I will appreciate
if you can find what is going on.

Best regards.

**Comment by Praxidice** [comment]
I did a debug build and let it run under the debugger for 48 hrs, but it didn't crash. I then ran the release build under the debugger and it did crash eventually with the same error (took roughly 60 hrs, but I didn't time it).

Release stack trace:

> 1  qwindows                                       0x7ffdd5623544 
2  qwindows                                       0x7ffdd5625ccd 
3  qwindows                                       0x7ffdd563356f 
4  qwindows                                       0x7ffdd563430b 
5  CallWindowProcW                      USER32    0x7ffe15265b6d 
6  CallWindowProcW                      USER32    0x7ffe1526583e 
7  glPushClientAttrib                   OPENGL32  0x7ffdd67e3919 
8  CallWindowProcW                      USER32    0x7ffe15265b6d 
9  DispatchMessageW                     USER32    0x7ffe1526573c 
10 IsWindowVisible                      USER32    0x7ffe15271ed3 
11 KiUserCallbackDispatcher             ntdll     0x7ffe1659fe34 
12 NtUserMessageCall                    win32u    0x7ffe14581184 
13 SendMessageW                         USER32    0x7ffe1526506b 
14 GetWindowTextW                       USER32    0x7ffe15264332 
15 MapWindowPoints                      USER32    0x7ffe15263a5f 
16 IsCompositionActive                  UxTheme   0x7ffe1168c58f 
17 IsCompositionActive                  UxTheme   0x7ffe1168bff1 
18 GetWindowTextW                       USER32    0x7ffe15263f9f 
19 qwindows                                       0x7ffdd56344b8 
20 CallWindowProcW                      USER32    0x7ffe15265b6d 
21 CallWindowProcW                      USER32    0x7ffe1526583e 
22 glPushClientAttrib                   OPENGL32  0x7ffdd67e3919 
23 CallWindowProcW                      USER32    0x7ffe15265b6d 
24 DispatchMessageW                     USER32    0x7ffe1526573c 
25 MBToWCSEx                            USER32    0x7ffe15275000 
26 KiUserCallbackDispatcher             ntdll     0x7ffe1659fe34 
27 NtUserPeekMessage                    win32u    0x7ffe145810c4 
28 PeekMessageW                         USER32    0x7ffe15269442 
29 PeekMessageW                         USER32    0x7ffe152693a9 
30 QEventDispatcherWin32::processEvents Qt5Core   0x7ffdb8513549 
31 qt_plugin_query_metadata             qwindows  0x7ffdd56834b9 
32 QEventLoop::exec                     Qt5Core   0x7ffdb84c54db 
33 QCoreApplication::exec               Qt5Core   0x7ffdb84c8631 
34 YACReaderLibrary                               0x7ff64c9b30de 
35 YACReaderLibrary                               0x7ff64ca72177 
36 YACReaderLibrary                               0x7ff64ca716ba 
37 BaseThreadInitThunk                  KERNEL32  0x7ffe14737bd4 
38 RtlUserThreadStart                   ntdll     0x7ffe1656ced1

Not terribly useful to tell what's going on. I'll try again with the debug build.

**Comment by Praxidice** [comment]
I'm pretty sure this is a bug in the Qt runtime. When I do a built with 5.14.2 it doesn't crash, but if I do a build with 5.12.4 it does crash. So I think just rebuilding with the new Qt version is all that is needed. I'm still not sure of the underlying reason of the crash though.

**Comment by selmf** [comment]
Thanks for taking the time to check this. The Qt runtime isn't perfect, as it is common with software of that scale ;) Mistakes happen and can be very annoying to track down.
As it isn't our fault in this case, I'll close this issue now. Feel free to reopen if it comes back.
