### ISSUE TITLE
Add PNG4 Support

### ISSUE THREAD

**Issue by ruschein** [YACReader/yacreader#135]
These days I find more and more digital comics that use PNG4.  They seem to be smaller than the JPEG versions put out by the same encoders.  I suspect that this would be rather easy to implement.  I might be willing to do it myself.  I have a MAC laptop to work on.  I don't have any experience working with QT but I have a fair amount of experience using C++.

**Comment by selmf** [comment]
I'm not sure what you mean by PNG4 but PNG files are already supported.

**Comment by ruschein** [comment]
You are right.  There were a bunch of digital comics tagged as PNG4 that have been showing up in recent weeks but it looks like they just work.  Another question: Are 7-Zip compressed files also supported and, if yes, which file extension should be used?

**Comment by selmf** [comment]
YACReader with (p)7zip backend (current Mac and Windows build) supports 7z, with unarr backend you need git builds of both YACReader and unarr.
Extensions are either .7z or .cb7.

Note that 7z is not a format I'd recommend for comics. Classic zip is much better if you want an open source format. If you really want 7z, I'd recommend to disable solid compression for better reading performance.

**Comment by selmf** [comment]
Closing as invalid ;)

**Comment by ruschein** [comment]
Well, I very occasionally find comics that are using 7z.  I guess I'll write a small shell script to convert those to cbz.  Thanks!

**Comment by selmf** [comment]
If you find them you can use them. I just don't recommend using that format for creating new ones or mass-converting to 7z from rar.
