### ISSUE TITLE
i can't build i can't find how

### ISSUE THREAD

**Issue by chooochoooo** [YACReader/yacreader#139]
So i don't know anything but i tried to change some. so i download qt(5.15) with little struggle and run qt creator.

but zip file was not opening and say (unable to load 7z lib from ./utils) and it was only run on creator also files are look different with publish version ,

 So i look up about qmake like INSTALL.md says but i didn't understand most of them, and i don't know how to build.

 all i did add environment variable (C:\Qt\5.15.0\msvc2019_64\bin)

and this is qmake
![image](https://user-images.githubusercontent.com/47330282/84384877-a334bb00-ac29-11ea-95af-216adcc0688a.png)
it says 'qmake-qt5' is not recognized as an internal or external command, operable program or batch file.
i don't know what i'm doing , i never compile wit prompt.

so how to make full release build?

apology about messy writing i'm not good at english. hope you can understand.

**Comment by selmf** [comment]
Hi @chooochoooo ,

the instructions in INSTALL.md are for Linux and other Unix installs. We don't have a guide for Windows (yet). You can use the Linux guide, but when using qmake on Windows, the steps need to be run like this:

>qmake CONFIG+=7zip
>nmake

or

>qmake CONFIG+=unarr
>nmake

There is no make install. @luisangelsm uses Innosetup to create an installer. The script he uses is under ci/win/create_installer.cmd on the develop branch.

There are some differences between the QtCreator build and the commandline build. The commandline build will put the build result to a different location, if I am not mistaken. When you launch from QtCreator that is not problem, but it is when you launch outside.

I hope this helps. If you have some time, please reduce the issue so it only describes the build problem and not your modifications. You can open a separate issue or a PR (if @luisangelsm is interested) for those.

**Comment by selmf** [comment]
@chooochoooo is your issue solved? Can I close this?
