### ISSUE TITLE
Spelling errors in README.md

### ISSUE THREAD

**Issue by dennerkrans** [YACReader/yacreader#141]
Nothing major but wanted to contribute to this amazing project :) 

I made a strike-through for the misspelled word followed by the correction, e.g. ~bringning~ bringing. 
***

# YACReader
"Yet another comic reader"
### License
This software has been developed by Luis Ángel San Martín Rodríguez ( [luisangelsm@gmail.com](mailto:luisangelsm@gmail.com) ) under GPL v3 license (see  [COPYING.txt](https://github.com/YACReader/yacreader/blob/develop/COPYING.txt) ).
### Getting YACReader
**Official releases:**
 [https://github.com/YACReader/yacreader/releases](https://github.com/YACReader/yacreader/releases) 
**As a package:**
 [<a href='68747470733a2f2f7265706f6c6f67792e6f72672f62616467652f766572746963616c2d616c6c7265706f732f7961637265616465722e737667.svg'>68747470733a2f2f7265706f6c6f67792e6f72672f62616467652f766572746963616c2d616c6c7265706f732f7961637265616465722e737667.svg</a>](https://repology.org/metapackage/yacreader) 
**From OBS build service:**

**Building from source:**
See  [INSTALL.md](https://github.com/YACReader/yacreader/blob/develop/INSTALL.md) 
### Contact
* Project home page :  [www.yacreader.com](http://www.yacreader.com/) 
* e-mail:
	*  [info@yacreader.com](mailto:info@yacreader.com) 
	*  [support@yacreader.com](mailto:support@yacreader.com) 
* Social:
	* Facebook -  [http://www.facebook.com/YACReader](http://www.facebook.com/YACReader) 
	* Twitter -  [https://twitter.com/yacreader](https://twitter.com/yacreader) 
	* YouTube -  [https://www.youtube.com/user/yacreader](https://www.youtube.com/user/yacreader) 
	* Instagram -  [https://www.instagram.com/yacreader/](https://www.instagram.com/yacreader/) 
If you need help or have any suggestion, please, send me an e-mail.
### Contributing
If you are interested in contributing to the project the first step should be to contact me so we can plan together the best approach, you can send an e-mail or just open an issue in this repo. For small bug fixes it is usually ok to open a PR directly.
Contributions are not restricted to code, you can help the project by ~bringning~ bringing new UI_UX ideas, designing new assets, ~writting~ writing manuals or tutorials, translating the apps, etc. If you are interested in DevOps, YACReader uses Azure Pipelines for CI_CD, any improvements in that area are welcome. Testing pre-releases is also really appreciated.
**Code**
YACReader uses clang-format to ensure a common style and avoid deviances from it. CI checks this and will fail if the correct format is not used. clang-format needs to be called ~recusivelly~ recursively in all the folders because some of them have the own .clang-format file, mainly to exclude changing the format in ~thirdparty~ third-party libraries which are included in the source code. I recommend to configure your development tools to use clang-format, you can try to use it manually, but please, do it always before ~commiting~ committing changes. I recommend using QtCreator configured properly, you can find a tutorial  [here](https://www.vikingsoftware.com/using-clang-format-with-qtcreator/) .
**CI/CD**
Any PR will be validated through CI, and it will not be merged if CI fails.
**Pull Requests**
The base and target branch for any PR should always be develop.
### Donations
YACReader is free but it needs money to keep being alive, so please, if you like YACReader, visit the home page and make a donation.

**Comment by selmf** [comment]
Thank you for spotting this. Could you submit a PR? That way I can just merge the changes and your contribution will be logged too.

**Comment by dennerkrans** [comment]
Sure thing :)
