### ISSUE TITLE
Documentation lists Qt >= 5.6 as a prerequisite but looks like Qt >= 5.8 is needed

### ISSUE THREAD

**Issue by Ponce** [YACReader/yacreader#15]
reading INSTALL.md and the CHANGELOG.md looks like Qt >= 5.6 is needed, so I tried to build latest 9.5.0 on the latest Slackware (I'm the maintainer on SlackBuilds.org), with qt-5.7.1 but I had these errors

make[1]: Entering directory '/tmp/SBo/yacreader-9.5.0/YACReader'
g++ -c -pipe -std=c++11 -O2 -fPIC -Wall -W -D_REENTRANT -fPIC -DNOMINMAX -DYACREADER -Duse_unarr -DLIBDIR=\"/usr/lib64\" -DDATADIR=\"/usr/share\" -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -I../common -I../custom_widgets -I../common/gl -I../custom_widgets -I../compressed_archive/unarr -I../shortcuts_management -I../QsLog -isystem /usr/include/poppler/qt5 -isystem /usr/include/poppler -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtOpenGL -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -I/usr/lib64/qt5/mkspecs/linux-g++ -o main.o main.cpp
main.cpp: In function ‘int main(int, char**)’:
main.cpp:86:11: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   comicId.setFlags(QCommandLineOption::HiddenFromHelp);
           ^~~~~~~~
main.cpp:86:40: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   comicId.setFlags(QCommandLineOption::HiddenFromHelp);
                                        ^~~~~~~~~~~~~~
main.cpp:87:13: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   libraryId.setFlags(QCommandLineOption::HiddenFromHelp);
             ^~~~~~~~
main.cpp:87:42: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   libraryId.setFlags(QCommandLineOption::HiddenFromHelp);

looking at the Qt documentation

http://doc.qt.io/qt-5/qcommandlineoption.html#setFlags

seems like some functions has been introduced with Qt >= 5.8.

**Comment by selmf** [comment]
Yes, that function sneaked in when I did some refactoring. You can use this patch to fix the problem:

https://gist.github.com/selmf/7bf4f4f208cf8a510cd99232db59d382

**Comment by Ponce** [comment]
thanks, @selmf ! I can confirm that compilation goes smooth here when the patch is applied.

**Comment by selmf** [comment]
Great! I'll leave the issue open until I've figured out what to do for Qt < 5.6.
