### ISSUE TITLE
Update build documentation

### ISSUE THREAD

**Issue by Anonymous-BCFED** [YACReader/yacreader#152]
First, the obvious:  I am aware that 20.04 is currently not being built against, so this is going to be an uphill battle anyway.

Second, the compile instructions are a bit outdated and confusing, since they attempt to guide the user through building the project using generic executable names and instructions which differ between platforms, distros, and even OS versions. On top  of this, the commandlines that *are* provided appear to be incorrect (or at least incorrectly formatted).

So, here are the problems I've run into thus far:

## Issues
1. `libunarr-dev` and `libunarr1` are [now available in the ubuntu repositories](https://packages.ubuntu.com/search?keywords=libunarr).
1. `qmake-qt5` is apparently just `qmake` now...?
1. Passing `OPTIONS+=` doesn't seem to affect anything. libunarr will be used regardless of passed options.
1. Using `qmake OPTIONS+=[7zip] make install` results in: <br /><pre>Cannot find file: make.<br>Cannot find file: install.</pre> I think someone meant to use a code block (`` ```code``` ``) rather than an inline block (`` `code` ``).

## Dependencies
In case it's useful, here's how I pulled in dependencies:
```
$ sudo apt install qt{base,declarative,script,multimedia,quickcontrols2-}5-dev libqt5opengl5-dev libqt5{multimedia,network,sql,script,scripttools,network}5 libqt5sql5-sqlite
$ sudo apt install libunarr-dev p7zip libpoppler-dev libqrencode-dev 
```

This isn't exactly a pristine build environment, and I have previously-existing packages floating around, so I may have missed something.

## Corrected Build Instructions
So here's what the build instructions should probably look like:

1. Run the two commands above to pull in Qt5, libpoppler, libqrencode, p7zip, and libunarr.
1. Execute `qmake` in the checkout directory.
1. Execute `make` to build your binaries
1. Finally, execute `sudo make install` if you want to install it.

**Comment by selmf** [comment]
Yes, this looks like the instructions got messed up a little on the last update, to the point that some of the info is wrong.

First of all, qmake. On some distributions that ship both Qt4 and Qt5 the command qmake-qt5 is needed. This is getting less and less common, so yes, it is just qmake now.

Passing OPTIONS+= will always fail. The correct syntax is like this:

> qmake CONFIG+=[Options]

As it is common in documenting commandline syntax the square brackets indicate that you need to replace them with the actual options, for example:

> qmake CONFIG+="7zip"

libunarr and 7zip are exclusive dependencies, i.e. you need only one of the two.

Building on Kubuntu 20.04 should not be a problem at all. For the record, I have just enabled the build for xUbuntu 20.04 on my OBS account and it worked smoothly. [You can get the package here.](https://software.opensuse.org/download/package?package=yacreader&project=home%3Aselmf)

**Comment by Anonymous-BCFED** [comment]
Yes, I should have mentioned that the build completed successfully.  Apologies on that detail, and thanks for the update.

**Comment by selmf** [comment]
I've updated the description so it is easier to understand the core issue and it is easier for us to remember that we need to update the docs.
