### ISSUE TITLE
Building from source Qt issue

### ISSUE THREAD

**Issue by MugenEnzan** [YACReader/yacreader#170]
Hi!

I hope I can get some guidance here. I installed almost all Qt packages just to get this thing to build but it still complains about this:
`Project ERROR: Unknown module(s) in QT: opengl
make: *** [Makefile:49: sub-YACReader-make_first] Error 3`

I made sure I have the qt multimedia package installed.

Any ideas?

This is on Pop!_OS 20.04

Thanks!

**Comment by selmf** [comment]
Here's the list of build dependencies I use for .deb packages:
`
qt5-qmake, qtbase5-dev, qtmultimedia5-dev, libpoppler-qt5-dev, qtscript5-dev, libqt5opengl5-dev, libunarr-dev, qtdeclarative5-dev
`
You're probably missing libqt5opengl5-dev ;)

**Comment by MugenEnzan** [comment]
_-facepalm-_

I spent a few days on google trying to locate this particular package and all answers i found pointed to qtmultimedia5 only. FML.

Seems to be building ok now. I wanted to update to the latest version but the debs weren't available on the usual repos on the site. This will probably be the best way forward in any case :D

Thanks for the help!

**Comment by selmf** [comment]
I haven't had the time to update our Debian packages. Ideally, this should be handled downstream but we don't have a third party packager to do this yet.
