### ISSUE TITLE
Increase the maximum zoom level

### ISSUE THREAD

**Issue by prantlf** [YACReader/yacreader#175]
I download mangas for off-line reading. I save them as a directory of images, packed to a ZIP archive. Some mangas have a very small default size of the picture. Zooming to 500% of the original size is not enough to be able to read them. For most of them helps the magnifying glass, but it is inconvenient. I found, that the convenient zoom would have to be 2000%, at least.

**How about increasing the maximum zoom value to 3000%?**

It would make the zoom slider more difficult to use and that is why I stretched to be twice the original width and moved it a little to the left.

Thank you!

Examples:

Not zoomed:

![not-zoomed](https://user-images.githubusercontent.com/733193/97103583-a5b22180-16ad-11eb-9e95-e87eef675c11.png)

Zoomed to 500%:

![zoomed-500](https://user-images.githubusercontent.com/733193/97103588-af3b8980-16ad-11eb-978c-0886ce172759.png)

Zoomed to 2000%:

![zoomed-2000](https://user-images.githubusercontent.com/733193/97103594-bb274b80-16ad-11eb-9108-085002746934.png)

**Comment by selmf** [comment]
Use "fit to width" instead of zoom.

- press "h" to unhide the toobar
- click on the symbol looking like this: <->

That's it!

**Comment by prantlf** [comment]
I see. The zoom operation is applied after the fit to * operation. Thank you!
