### ISSUE TITLE
"page not available" maybe problems with .png

### ISSUE THREAD

**Issue by TristisOris** [YACReader/yacreader#180]
never seen that before. cant view all .png pages from this archives. Downloaded from https://readmanga.live/semia_shpiona/vol3/12?mtr=#page=1

files not corrupted, can open them directly from archive.

https://yadi.sk/d/TyhvM9G6kLWJUg

**Comment by fire-eggs** [comment]
The .png files in the archive are 8-bit greyscale. This is a rather unusual PNG format. 

I have several manga reader programs and image viewer programs, and many of them fail to display those images.

[Spy x Family! Very fun!]

**Comment by selmf** [comment]
Not sure what is causing this, probably a library problem outside of the scope we can fix. Too much missing information. Please provide at least the info which version of YACReader you are running on which platform/operation system.

**Comment by fire-eggs** [comment]
I saw the issue with YacReader 9.7.1 running on Linux Mint 20 (x64). But I'm not the OP.

**Comment by TristisOris** [comment]
v9.7.1.2009123-winx64

so problem in encoding, any chances to fix it in library? even other programs affected too.

**Comment by selmf** [comment]
The problem with the images you provided is not the 8-bit grayscale format but faulty eXIf data which causes libpng to reject the images. Some applications who ignore the eXIf header or have workarounds for this can display them, others just relying can't. So the fault is on the side of whoever created these images.

`WARN  2020-12-30T09:29:54.202 libpng warning: eXIf: CRC error 
WARN  2020-12-30T09:29:54.202 libpng warning: eXIf: incorrect byte-order specifier 
`

And here's some data from pngcheck:

`ERROR: 0012 Chapter\0002.png
0012 Chapter\0003.png  illegal (unless recently approved) unknown, public chunk eXIf
`
Conclusion: Even if they can be displayed by some apps, the problematic images contain bad data and are corrupt. Simple solution? Strip the eXIf data. There are tools for this.

**Comment by fire-eggs** [comment]
Good to know! Thank you, I learned two new things today!

**Comment by selmf** [comment]
Closing this, as it is not our bug and there's not much we can do about it.
