### ISSUE TITLE
FYI: WEBP support not available "out of the box" [Linux Mint]

### ISSUE THREAD

**Issue by fire-eggs** [YACReader/yacreader#182]
On Linux Mint 20, using YacReader 9.7.1. Found that WEBP support wasn't working - had to install the `qt5-image-formats-plugins` package.

Might be worth a mention / FAQ.

**Comment by selmf** [comment]
The image formats module is listed as a dependency in the build instructions and is also an optional (i.e. suggested) dependency for the Debian packages. IMHO that should be enough.

**Comment by fire-eggs** [comment]
Fair enough! Thanks for the tip!
