### ISSUE TITLE
Strange Windows Build Error

### ISSUE THREAD

**Issue by LordDeimos** [YACReader/yacreader#20]
I've been trying to build the windows executables in order to start assisting the development, but for the life of me I can't get it to make. I'm trying to build it on cygwin with the mingw64 64bit toolchain for qt5 and have managed to get the pri files to work with it (added extra unix:cygwin... steps which mirror the win32 steps) but when trying to run the makefile it throws out an error "expected unqualified-id before string constant", it doesn't give a line number, source file or any other helpful detail I could use to diagnose the issue.

If anyone else has run into this problem or know where the issue might be that would be really appreciated. My fork has the pri changes if you would like to review those.

**Comment by selmf** [comment]
As you probably already discovered, the Windows build system of YACReader was written with MSVC in mind. This includes compiler flags we set in the .pro files, so I doubt that editing the .pri files is enough to port the build system to mingw or msys2. You probably have to port the llvm/gcc compiler flags from the unix build as well. Another possible pitfall are the prebuilt dlls we supply for the Windows build. These are built with MSVC too, so you will need the MSVC runtime to make it work.

**Comment by LordDeimos** [comment]
Thanks for the info, I'll stick to using msys for now, as it is working, when I get more comfortable with the infrastructure I'll look into it. For now, I will just try and wrap my head around the code so I can start helping out.

**Comment by selmf** [comment]
Thanks. If you encounter any build system issues, feel free to report them. Our build documentation is still largely oriented at Linux and needs a bit of work to cover the other platforms too.
