### ISSUE TITLE
Last comics in the list don't show up as read and the page number doesn't jump to the last

### ISSUE THREAD

**Issue by cooperspencer** [YACReader/yacreader#21]
I am on Linux and if I read the last comic in the list, it doesn't show up as read after I am done with it.
If I stop on the second to last page and close yacreader, the page shows up in the overview. If I then reopen it and read the last page and close it, it is still on the second to last page.
If I can help with anything, please let me know.

ps: Everything is local, I don't read anything over the network.

**Comment by selmf** [comment]
Thanks for reporting this here. I think this actually might be a variant or regression of a known bug. Some users reported similar problems when reading in double page mode. Is this also happening in double page mode for you?

**Comment by luisangelsm** [comment]
Fixed on develop.
