### ISSUE TITLE
The current index should be reset to 0 in Library Grid comics view when the model is replaced

### ISSUE THREAD

**Issue by vedgy** [YACReader/yacreader#210]
### Steps to reproduce
1. Start YACReader Library and switch to Grid comics view.
2. Select a non-top-left cover.
3. Switch to a different folder or reading list, or enter something into the search line in order to replace the model and change the comics displayed in the Grid view.
4. Transfer focus to the Grid view without changing its selected or current item, e.g. click on a space between covers.
5. Press an arrow key, e.g. Down.

#### Observed result
The move in the direction defined by the pressed arrow key starts from the index selected in the previous comic list.

#### Expected result
The move starts from the highlighted in the UI top-left cover at index 0.

### Additional information
I think this bug occurs because [`GridView.currentIndex`](https://github.com/YACReader/yacreader/blob/93596a49729ff49c8d6e1759b5f89a3ca986e269/YACReaderLibrary/qml/GridComicsView.qml#L700) is not reset when the model is replaced in [`GridComicsView::setModel()`](https://github.com/YACReader/yacreader/blob/93596a49729ff49c8d6e1759b5f89a3ca986e269/YACReaderLibrary/grid_comics_view.cpp#L237). But the relevant code looks complex to me, especially since I am not experienced in QML. So I don't know how to reset this variable to 0 whenever the model is replaced.

**Comment by luisangelsm** [comment]
Fix pushed to develop.
