### ISSUE TITLE
AUR Package build failure gn:141 set_sorces_assignemnt_filter argument must be an empty list

### ISSUE THREAD

**Issue by Dashon1** [YACReader/yacreader#217]
Hey. I'm new to arch and I was trying to install yacreader from the aur when I ran into the following error message.
ERROR at //build/win/BUILD.gn:14:1: set_sources_assignment_filter argument must be an empty list.
set_sources_assignment_filter(deprecated_default_sources_assignment_filter)
^-------------------------------------------------------------------------
See //testing/test.gni:232:9: which caused the file to be included.
        "//build/win:default_exe_manifest",
        ^---------------------------------
==> ERROR: A failure occurred in build().

Any idea what went wrong here?

**Comment by selmf** [comment]
This is not a YACReader bug, but a build issue in one of the dependencies. If you are new to arch, make sure you read the arch wiki article on the AUR and especially AUR helpers.
I think you already tried to report this on the libpdfium-nojs package on the AUR but deleted the comments? I am the maintainer of this package and I am looking into the issue, but this takes time.
Here is not the right place to report or discuss this.

**Comment by Dashon1** [comment]
Will do. I don't think I might have accidentally reported and deleted the comments when trying to fix the package. My bad.

**Comment by selmf** [comment]
It looks like this is a regression in the build system caused by the latest gn update. You can try to:
- downgrade gn (look into the arch wiki for instructions)
- or: build a beta version of libodfium-nojs. For this you need to edit the PKGBUILD - comment out line 47 and uncomment the line below that. It should have a "channel=beta" in the url

**Comment by Dashon1** [comment]
Alright will do.

**Comment by Dashon1** [comment]
Tried building with the beta version of libodfium-nojs. It made it a lot farther into the build process, but ultimately threw a different error. 
/usr/bin/ld: cannot find -lunarr
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:652: YACReader] Error 1
make[1]: Leaving directory '/home/d-air1/.cache/yay/yacreader/src/yacreader-9.7.1.2009123/YACReader'
make: *** [Makefile:49: sub-YACReader-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
checking dependencies...

Now I'll try after downgrading gn

**Comment by selmf** [comment]
That is not a pdfium problem anymore. No need to try downgrading gn.

The problem you are encountering here is a missing package unrelated to libpdfium. This is, again, not a YACReader problem but this time it is a problem in the AUR helper you are using, YAY. As I wrote before, you need to familiarize yourself with the AUR if you want to use arch linux. AUR helpers are fancy and helpfull, but ultimately totally unsupported. If you'd build the YACReader package using the official manual process using makepgk, you would not encounter this error.

**Comment by Dashon1** [comment]
Oh. I see. I did in fact get a build error after downgrading gn. I'll do it manually and try to familiarize myself with aur helpers more. Thanks for your time.

**Comment by selmf** [comment]
The package you will need is libunarr, also from the AUR. It is a dependency of the YACReader package and yay should not have missed it.

**Comment by Dashon1** [comment]
Hey, so after viewing the wiki and looking up the official way to install things from the aur. I git cloned the libunarr package from the aur and ran makepkg -si. That compiled and installed fine. I couldn't compile yacreader just yet because it was complaining about not having libpdfium another package which was in the aur. I attempted to follow the same steps from the wiki here. However, libpdfium-nojs doesn't wanna compile now. Here is the error message I get from that:
Could not run pkg-config.

See //build/linux/BUILD.gn:10:3: whence it was called.
  pkg_config("gio_config") {
  ^-------------------------
See //build/config/freetype/BUILD.gn:10:24: which caused the file to be included.
    public_configs = [ "//build/linux:freetype_from_pkgconfig" ]

**Comment by selmf** [comment]
You are missing the base-devel dependency that is assumed to be installed by all AUR packages, so it is not included in the dependencies. Read https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started to see how to set it up, ist is right at the top.

**Comment by Dashon1** [comment]
Actually I had already visited that page. I definitely have the base-devel packages installed.
Output of "pacman -S --needed base-devel":
Thu 18 Feb 2021 07:01:01 AM CST
warning: autoconf-2.71-1 is up to date -- skipping
warning: automake-1.16.3-1 is up to date -- skipping
warning: binutils-2.36.1-2 is up to date -- skipping
warning: bison-3.7.3-1 is up to date -- skipping
warning: fakeroot-1.25.3-2 is up to date -- skipping
warning: file-5.39-1 is up to date -- skipping
warning: findutils-4.8.0-1 is up to date -- skipping
warning: flex-2.6.4-3 is up to date -- skipping
warning: gawk-5.1.0-1 is up to date -- skipping
warning: gcc-10.2.0-6 is up to date -- skipping
warning: gettext-0.21-1 is up to date -- skipping
warning: grep-3.6-1 is up to date -- skipping
warning: groff-1.22.4-4 is up to date -- skipping
warning: gzip-1.10-3 is up to date -- skipping
warning: libtool-2.4.6+42+gb88cebd5-14 is up to date -- skipping
warning: m4-1.4.18-3 is up to date -- skipping
warning: make-4.3-3 is up to date -- skipping
warning: pacman-5.2.2-2 is up to date -- skipping
warning: patch-2.7.6-8 is up to date -- skipping
warning: pkgconf-1.7.3-1 is up to date -- skipping
warning: sed-4.8-1 is up to date -- skipping
warning: sudo-1.9.5.p2-1 is up to date -- skipping
warning: texinfo-6.7-3 is up to date -- skipping
warning: which-2.21-5 is up to date -- skipping
 there is nothing to do

The error is still the same.

**Comment by selmf** [comment]
Ah sorry, it looked like a common beginners error so I assumed it was that. The error with pkg_config should not happen when it is installed correctly. I don't know what is causing the error, but I think in your case it might be a good idea to do a clean build just in case old leftover build files are giving you trouble. Delete the source and build directories and rerun the build to see what happens.

**Comment by Dashon1** [comment]
Alright. I'm gonna go to bed for now, and take another whack at it when I wake up. Thanks again for all your help and guidance.

**Comment by Dashon1** [comment]
Alright. I'm back at it again. Started with a clean build by simply deleting all the cloned directories that I downloaded and starting over. Unfortunately I got the same result.

**Comment by Dashon1** [comment]
Is there a cache that I'm unaware of that would have interfering files outside of my build directory?

**Comment by selmf** [comment]
Usually there is the sources downloads by makepkg and the build directory with a source dir and a build dir. You can run makepkg -C to delete the sources. I tried to reproduce the error you are having and I can confirm that the current version of gn does not work with the current stable version of libpdfium. The version before works fine though.
I sadly can't reproduce your current error. Did you switch back to the unmodified PKGBUILD before building with the downgraded version of gn? For me the build works with gn 0.1831 and is broken with 0.1859

**Comment by Dashon1** [comment]
Alright, so now my goal should be to run makepkg -C to clean the source packages in addition to downgrading gn. Then I'll start with a clean build dir as well. I'll see how it goes.

**Comment by Dashon1** [comment]
Yes I did switch back to the unmodified pkgbuild before I downgraded gn. I was attempting to only try one solution at a time.

**Comment by selmf** [comment]
Or you wait until I have time to fix the package for the current gn ;)

**Comment by Dashon1** [comment]
Best of luck to you and thanks for everything. I'll probably tinker with it a bit more. Its not a big deal or anything. I even grabbed the binaries from the fedora rpm and made it work that way. I can use that if I really need to use the app. However, trying to solve this issue has lead to me learning much more about arch, so I'll see what I can do on my own now.
