### ISSUE TITLE
Feature Request: option to hide title bar

### ISSUE THREAD

**Issue by dsanson** [YACReader/yacreader#22]
It would be neat if there was an option to hide the title bar, for those of us who are using tiling window managers (like chunkwm) on OS X.

It is easy enough to do this by adding a line to main_window_viewer.cpp:

        setWindowFlags(Qt::CustomizeWindowHint | Qt::NoDropShadowWindowHint);

I have successfully compiled my own copy that disables the title bar in this way, but I saw that there is 
commented out code for an "always on top" configuration option that looks like it could easily be adapted to this purpose as well?

**Comment by selmf** [comment]
I'm not sure if we can justify implementing this. There are probably not a lot of users who would profit from it and, speaking from experience, messing with window flags is risky. Even if everything seems to work fine for you, it can wreak havoc for other users depending on their hardware and os.

If you can make it foolproof Luis might accept it as a patch though.
