### ISSUE TITLE
C++17 in YACReader

### ISSUE THREAD

**Issue by selmf** [YACReader/yacreader#230]
> I'm all for increasing minimum supported Qt version in order to be able to use things like qOverload and other features introduced between versions 5.6 and 5.9. Ubuntu 16.04 is supported only until April 30th, 2021. Could we perhaps increase the C++ standard version to C++17 too? Ubuntu 18.04's GCC 7.4 supports almost all C++17 features: https://gcc.gnu.org/projects/cxx-status.html#cxx17 and https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2017. If we don't have to support old Clang and MSVC versions, C++17 should be almost completely supported on Mac and Windows too. The newer standard makes development more fun and motivating.
> - @vedgy in #228

> About c++17, since Qt6 adopts c++17 and we want to move in that direction I think it is reasonable to start using it too.
> - @luisangelsm in #201 

I have copied these here so the discussion has a proper place.

IMHO moving to c++17 is the obvious next step, but we should consider when to do it. Personally I would prefer to get our code into a better shape first, so we've got our backs covered before marching forward. I'm not thinking about big rewrites here but more along the lines of elimination of deprecated code, tool assisted refactoring for stuff like old style SIGNAL SLOT connects and the like.

There is also the question of build chain support. Qmake 5.9 does not support CONFIG+=c++17, so we will have to add it to the compile flags manually. Porting or testing to Qt6 will make little sense before Qt 6.2 is released since Qt6 does not provide all modules we require yet, so it is unlikely we will do that for YACReader 9.8.

This would make C++17 a good milestone for YACReader 9.9, at which point we also could re-asses the Ubuntu situation regarding full C++17 support.

Until then we could treat this like we have done for older Qt versions in the past - use modern c++17 functions where appropriate, provide fallback solutions where necessary and restrict newer functionality to newer systems if that is too complicated.

**Comment by luisangelsm** [comment]
I think we can use `CONFIG += c++1z` to enable c++17 in Qt5.9

**Comment by vedgy** [comment]
> I think we can use CONFIG += c++1z to enable c++17 in Qt5.9

That would be great. But if it [doesn't work](https://doc.qt.io/archives/qt-5.9/qmake-variable-reference.html#config), we can at least enable c++14 for now.

> This would make C++17 a good milestone for YACReader 9.9, at which point we also could re-asses the Ubuntu situation regarding full C++17 support.

Do you mean that YACReader has to support Ubuntu 16.04 until its EOL date? Or that we don't necessarily have to support Ubuntu 18.04's GCC 7 and might be able to bump the requirement to Debian Stable's [GCC 8](https://packages.debian.org/buster/gcc)?

**Comment by selmf** [comment]
No, we don't need to support Ubuntu 16.04 till its EOL. We may choose to do so if backported packages for our dependencies are available, but I am against making this a hard requirement. For Ubuntu 18.04 we should check for a suitable backport package with a compiler that offers full support for C++17. We may also choose to just use Ubuntu 20.04 for our builds instead, but compatibility with 18.04 is likely important to our Linux Mint users, so it makes sense to use it.
Whatever Debian stable uses is usually a good choice for requirements, but the Ubuntu and derived community tend to hang to a LTS releases pretty long, so it doesn't hurt to take that into account.

**Comment by vedgy** [comment]
> IMHO moving to c++17 is the obvious next step, but we should consider when to do it. Personally I would prefer to get our code into a better shape first, so we've got our backs covered before marching forward. I'm not thinking about big rewrites here but more along the lines of elimination of deprecated code, tool assisted refactoring for stuff like old style SIGNAL SLOT connects and the like.

Unlike porting away from deprecated code and tool-assisted refactoring, switching to a newer C++ standard might require only trivial effort, if everything compiles right away. And being able to use newer standard features may make the porting somewhat easier. I think the biggest question and possible hurdle is whether all 3rd-party dependencies support C++17.

Almost every C++17 standard and library feature is available in GCC 7. So worrying about its incomplete support should not delay the switch. Any unsupported feature by any platform will be caught by the CI right away, if only the CI's Clang and MSVC versions *are* the minimum supported ones.

**Comment by selmf** [comment]
Well, we could always create a PR request which changes the std to c++1z and see if it makes our CI throw a fit. If everything passes, we merge it when it is convenient, if not we start fixing things.
If possible, I would like to avoid introducing c++17 as a hard requirement for YACReader 9.8 though.

**Comment by vedgy** [comment]
#232 implies that switching to *c++1z* is likely to be smooth.

What are the minimum compiler versions YACReader should aim to support? Our current CI versions:

1. [Ubuntu 18.04's GCC 7.4.0](https://packages.ubuntu.com/bionic/gcc) is fresh enough for now.
2. [Clang 11 or even 12](https://github.com/actions/virtual-environments/blob/macOS-10.15/20210302.1/images/macos/macos-10.15-Readme.md) is very fresh indeed. Do we need to support earlier Clang versions?
3. *MSVC\14.16.27023*, that is *Visual Studio 2017 version 15.9* is pretty old, but almost completely supports C++17 according to [cppreference](https://en.cppreference.com/w/cpp/compiler_support#C.2B.2B17_features).

> If possible, I would like to avoid introducing c++17 as a hard requirement for YACReader 9.8 though.

In order to support an older compiler/distribution version? Is there some specific target you want YACReader 9.8 to support or are you just generally cautious about suddenly increasing requirements? Perhaps we could make the process gradual by switching to C++14 before and to C++17 after YACReader 9.8 is released?

**Comment by selmf** [comment]
As a general rule of thumb I try to avoid introducing requirements without a specific need. While I generally support switching to a newer C++ baseline, there is a slim possibility that this will give me or another downstream packager trouble when building YACReader for the users.
There is not really a specific target I have in mind with this request, but YACReader carters to a lot of LTS users on Linux and we also have downstream packagers for even less used operating systems like the BSD family and Haiku OS. Making the transition to C++17 a clean cut after the release of YACReader 9.8 might be over cautious, but it will ensure we can still supply 9.8 to a wide range of users and it also has the advantage that we start the transition to newer C++ at the beginning of a new development cycle and not at the end of the current release sprint.

In my opinion there is little value in switching to C++14 first. If we're going to raise the bar, we should do it properly.

By the way, it seems that we should add **both** c++1z and c++17 to CONFIG in qmake for best compatibility - at least that is what QtCreator is doing for their build.

**Comment by luisangelsm** [comment]
Done as part of the migration to Qt6
