### ISSUE TITLE
7-zip error

### ISSUE THREAD

**Issue by JohnBlood** [YACReader/yacreader#24]
I had version 9.0 installed on my Widows laptop. I installed 9.5 with 7zip support. Now it wont open any comic files.

**Comment by selmf** [comment]
Hard to tell what's going on without a bit more info. Which version of Windows? Does the application start up at all? Are you seeing any error messages?

**Comment by JohnBlood** [comment]
Sorry for the delay in replying. I first installed version 9.0 on my Windows 7 64-bit laptop and it worked without any problem. Then I downloaded and installed 9.5 with 7zip support. The library application works okay, but if I try to open any of the comics I get this error: "unable to load 7zlib from ./utils".

![yacreader-error](https://user-images.githubusercontent.com/5157847/43682934-667cb56c-9850-11e8-9356-1cf11fd22641.png)

**Comment by luisangelsm** [comment]
Hmmm, I am not sure if this is a Windows 7 related issue. But the library is there, I just tested right now.

Uninstall completely the app, then double check that the installation directory is gone, if not delete it manually and finally install the app again.

**Comment by JohnBlood** [comment]
@luisangelsm I'll give that a try. When I said "library", I meant the YACReader Library. That part of the application works fine.

**Comment by JohnBlood** [comment]
I uninstalled and reinstalled the application. It works just fine now.

**Comment by selmf** [comment]
Great! Closing the issue …
