### ISSUE TITLE
Regression since 9.7.1: setting a folder as uncompleted/read/manga is not preserved between Library launches

### ISSUE THREAD

**Issue by vedgy** [YACReader/yacreader#241]
### Steps to reproduce:
1. Run YACReaderLibrary built from the current *develop* branch.
2. Right-click a folder in a folder view and set it as uncompleted and/or read and/or manga.
3. Restart YACReaderLibrary and take a look at the previously edited folder, right-click on it and examine the context menu.

#### Observed result
The folder is completed, unread and not a manga.

#### Expected result
The folder status and type is correctly stored in the DB and restored in the UI when Library is restarted.

### Additional information
Lines like these appear in the output of Library built in Debug mode:
```
WARN  <date+time> QObject::connect: No such signal LibraryCreator::failedUpdatingDB(QString) in ../../yacreader/YACReaderLibrary/library_window.cpp:1048 
WARN  <date+time> QSqlQuery::value: not positioned on a valid record 
WARN  <date+time> QSqlQuery::value: not positioned on a valid record 
...
WARN  <date+time> QSqlDatabasePrivate::addDatabase: duplicate connection name '/path/to/library/dir/.yacreaderlibrary7fa2c0909540', old connection removed. 
WARN  <date+time> QSqlQuery::value: not positioned on a valid record 
WARN  <date+time> QSqlQuery::value: not positioned on a valid record 
...
```

**Comment by luisangelsm** [comment]
I can't replicate this on the latest dev build `9.8.0.2104301` (tested on Windows)

**Comment by vedgy** [comment]
Just checked: the bug is still reproducible at the latest *develop* branch commit on my system (Manjaro GNU/Linux with latest updates). I don't think that the cause is an accidental database corruption, because I could reproduce the bug with a freshly created library. Perhaps the bug is platform-specific or depends on a version of one of the dependencies... Do you have the same errors in Library output? I think the numerous `QSqlQuery::value: not positioned on a valid record` warnings correspond to this bug.

**Comment by luisangelsm** [comment]
No, I don't see those warnings in debug mode. I also tested it on macOS.

Do you mind creating a small library to see if the bug depends on the DB state?

**Comment by vedgy** [comment]
I think I have already tried this before. Just to be sure, tried again:
* created a library with a single comic inside a single directory in *develop* version (built in Qt Creator) => the bug exists;
* deleted the just created library;
* created a library with a single comic inside a single directory in *9.7.1* version (system-installed, built from [AUR](https://aur.archlinux.org/packages/yacreader/)) => no bug.

One more possibility is that the bug somehow depends on how YACReader is built or against which library versions. 

@selmf, could you try to reproduce this issue on your GNU/Linux system?

**Comment by luisangelsm** [comment]
I found it, "manga" field is added to existing libraries on migration but the `folder` table is created without it on fresh libraries.

**Comment by luisangelsm** [comment]
Pushed a fix to `develop`.

**Comment by vedgy** [comment]
The fix eliminates the bug for a newly created library. Thanks!
An already existing broken library can be fixed by manually adding the "manga BOOLEAN DEFAULT 0," field into the *folder* table (e.g. by editing *\<library folder\>/.yacreaderlibrary/library.ydb* in [DB Browser for SQLite](https://sqlitebrowser.org/)).
