### ISSUE TITLE
Gentoo Linux 7z lib error

### ISSUE THREAD

**Issue by lehitoskin** [YACReader/yacreader#254]
I have compiled YACReader v9.8.0 from source on Gentoo using the p7zip backend. I have installed it into `/usr/local`, but whenever I try to load any comic book file, I get this error window:
![2021-05-20-204455_500x204_scrot](https://user-images.githubusercontent.com/2506703/119079336-c248da80-b9ac-11eb-8999-b305d59523e9.png)
I followed the instructions to a T, but I can't figure out what's going wrong.

**Comment by selmf** [comment]
The p7zip backend consists of two components - the headers which you create by adding the p7zip source code to the YACReader compilation and the 7z libraries plus the rar codec supplied by the system.
To make it work on Linux, you need to have a compatible version of these libraries installed at LIBDIR/yacreader or LIBDIR/p7zip. LIBDIR defaults to /usr/lib but can be set to other values at compile time.
As long as Gentoo is shipping p7zip 16.02 you should be able to make it work by installing p7zip as a package and it should just work. If Gentoo updates to a newer version you can place the old libraries in LIBDIR/yacreader and YACReader will use these.

The error message refers to the path YACReader uses under OS X and Windows and is a little confusing. We should probably change it for Linux.

**Comment by lehitoskin** [comment]
Thank you for the insights. I got it to work by recompiling `app-arch/p7zip` with `USE=rar` and then had to run `sudo ln -sv /usr/lib64/p7zip /usr/local/lib/p7zip` and now it works. Weird that it _only_ looks in `/usr/local` and _only_ inside the `lib` folder and not the `lib64` folder.

**Comment by selmf** [comment]
Not weird at all. You can see the code here:

https://github.com/YACReader/yacreader/blob/develop/compressed_archive/compressed_archive.cpp

If you feel like improving it, feel free to have a go at it. Contributions are welcome :)

**Comment by lehitoskin** [comment]
It looks like the library directory is defined simply as `LIBDIR = $$PREFIX/lib` in the .pro files rather than doing any real system library detection. I digress, my issue has been fixed and for now I am satisfied.
