### ISSUE TITLE
Add shortcuts for moving to the next/previous pages.

### ISSUE THREAD

**Issue by samiksome92** [YACReader/yacreader#257]
Currently when we navigate YACReader flips a single page when it is in single page mode and flips two pages when in double page mode. If it encounters wide images it flips only a single page even in double page mode so that it can show the wide image during the next flip.

Sometimes there are comics which have double pages as split images rather than a single image. In such a case unless the first image is a even numbered image and the second one odd, using double page mode shows the images in different flips. This can be fixed by using the goto function to manually flip a single page rather than the default two pages in double page mode.

While goto works it is rather cumbersome since you have to manually type in the next/previous page number. Adding a shortcut for going to the next/previous page will be useful.

I have added the functionality here: https://github.com/samiksome/yacreader/commit/d024b38d3e8c2d07a01569db03736b279cd9ca38

It's implemented simply as `goTo(currentIndex + 1)` and `goTo(currentIndex - 1)`. I have bound the default shortcuts to `.` and `,` respectively. It seems to work fine however there is one issue. Normally in double page mode if the next two pages involve a narrow and a wide image only the narrow image is shown. However when moving back if there happens to be a wide and narrow page the pages are shifted (one page flipped) instead of showing only the narrow image.

Any feedback is appreciated.

**Comment by luisangelsm** [comment]
Done here: https://github.com/YACReader/yacreader/commit/f3249e405321ce76df4d550237b18c8d42fcb2e8
