### ISSUE TITLE
[Feature Request] read comic from folders

### ISSUE THREAD

**Issue by imKota** [YACReader/yacreader#267]
Add support for reading from folders. I have about 2TB of comics, and they are all stored in folders, and it will take a very long time to archive each one.

**Comment by selmf** [comment]
We already support that.

**Comment by imKota** [comment]
> We already support that.

@selmf YACReaderLibrary doesn't work with folders. With archives only.

**Comment by luisangelsm** [comment]
This has been requested some times, it is doable but it introduces an extra layer of complexity. Compressing all those folders you have can easily be done using a script...so unless you want to have those comics uncompressed I recommend you to try to automate the process and zip them.

**Comment by selmf** [comment]
Btw, you don't really need to compress them. Zip and rar can be set to a compression level of 0, which just stores the files in an archive without compressing them. This should be fast to convert and just as fast as uncompressed folders to open.
