### ISSUE TITLE
Question about building with MSYS2/MinGW64

### ISSUE THREAD

**Issue by eddiezato** [YACReader/yacreader#273]
I managed to build with `msys2/mingw64`, but only by removing this line.. Can anyone explain what this line means and how necessary it is?

https://github.com/YACReader/yacreader/blob/ca81b5424a33346bcc38f644545aa752c919cc3e/YACReader/YACReader.pro#L60

I use the qt plugins for avif and jpegxl, which I built with `msys2/mingw64`, and I need yacreader to be built with it as well.

P.S. I understand `QMAKE_CXXFLAGS_RELEASE` itself, but am confused by the added flags.

**Comment by selmf** [comment]
These flags are intended for the MSVC compiler, so they are not compatible with the GCC based mingw64 and msys2. If your build runs fine there is probably no need to worry about this. Flags are usually set by Qt's platform specs and there is a good chance this is a leftover from a bugfix or workaround that no longer is needed.

**Comment by eddiezato** [comment]
@selmf thanks for the quick response. So far, I don't see any problems with my build.
