### ISSUE TITLE
After Ctrl+O to open a new directory, the windows loose the focus, can't navigate

### ISSUE THREAD

**Issue by rangzen** [YACReader/yacreader#278]
Hello,
I don't know if it happens only on Linux but when you do Ctrl+O to open the next chapter for example, the window seems to loose the focus so the arrow keys don't work. You have to click on the windows and then you can turn pages.
Thank you!

**Comment by luisangelsm** [comment]
It doesn't happen in Windows. Could it be related to the window manager you are using?

**Comment by rangzen** [comment]
Sure. I will test this behavior on Windows

**Comment by rangzen** [comment]
I upgraded KDE and it's working now so you were probably right about the window manager. Sorry...
