### ISSUE TITLE
Error Server Version on iOS (YACReaderLibraryServer - Raspberry)

### ISSUE THREAD

**Issue by matheusfaustino** [YACReader/yacreader#28]
Hello,

I'm trying to setup a server using my raspberry pi 3 model B and I'm getting an error with the Title Server Version in the iOS app. It says: "You need YACReaderLibrary 9.5.0 or higher".

The error is pretty clear, but the problem is that I created the lib using the version 9.5.0. 

I tried to upgrade a old version lib (9.0.0) using the YACReaderLibraryServer by command line, without success. I tried upgrading the lib using the desktop version, but nope and I tried creating a new one, using the desktop version 9.5.0, but sadly the same erro. 

The problem seems to be related with the iOS app, because I can import, without problem, using the desktop app.

I don't know what more I can do :p could you help me, please?

Thanks in advance.

iOS version: 3.0.1
Desktop: W10
Raspberry pi: 3 Model B
Raspberry OS: Linux raspberrypi 4.14.50-v7+
YACReaderLibraryServer 9.5.0
![yacserver-version](https://user-images.githubusercontent.com/5246304/44316747-c4e50280-a403-11e8-8217-b6e7b14adeb5.PNG)
![yac-version-desktop](https://user-images.githubusercontent.com/5246304/44316748-c4e50280-a403-11e8-99ee-8fd24cc6abf8.PNG)

**Comment by selmf** [comment]
Hi matheusfaustino,

I'm not sure what could be causing this. YACReaderLibrary and YACReaderLibraryServer use the same code to do their work. I don't have an iOS device, so I can't test the problems. I'll assign @luisangelsm to this, but it might take a little time before he can have a look.

**Comment by matheusfaustino** [comment]
Hi @luisangelsm, just YACReaderLibraryServer is running. I tried restarting it, but without success, sadly. Actually, I tried a lot of ways: desktop version closed - server on, server restart, desktop version running - server on, HQ lib created by desktop version, upgraded by desktop version, upgraded by YACReaderLibraryServer and so on. 
I didn't try creating using YACReaderLibraryServer, but I think that would take a while.

Is there a place to get from LibraryServer log or something like that?

If you want to, I can test the app using TestFlight too.

**Comment by matheusfaustino** [comment]
Thanks for your attention @selmf  ^^

**Comment by matheusfaustino** [comment]
Hi, I tried again and I received a different message when I clicked to connect (not browse) in the setup.
![clicked to connect](https://user-images.githubusercontent.com/5246304/44497156-36b08c80-a64e-11e8-8e05-09353e5bf126.jpg)
![clicked to browse](https://user-images.githubusercontent.com/5246304/44497166-47610280-a64e-11e8-9d71-fd07167b1066.jpg)

**Comment by selmf** [comment]
Actually, I have one more idea we could try to diagnose this. Could you run Wireshark or something similar to record what's happening when you try to connect to the libraries?

Also, @luisangelsm could have a look at your library (just the hidden directory with the database, not the actual comics) to see if there is a problem there and try to reproduce it.

**Comment by matheusfaustino** [comment]
sorry for the delay :( 
I was trying out wireshark and then I tested a different port for the YACReaderLibrary on raspberry (I'm already running apache on default port) and with a different port it worked \o/ .
I think the message is misleading. Maybe give another message would be great. I don't have experience with C++ but I can test. 

I gonna close it, but it's not a bug, it's not an accurate message.
But thanks for your time and help ^^
