### ISSUE TITLE
Configure files of YACReaderLibraryServer

### ISSUE THREAD

**Issue by chinanoahli** [YACReader/yacreader#280]
I am trying to creat a docker for YACReaderLibraryServer.

Something make me confused, which path I should share with host (except of the comic path), to storage the config of the YACReaderLibrary Server?

And there any default path of YACReaderLibrary scan comics each time when YACReaderLibraryServer starts?

Like:
```
~/.local/share/YACReader/YACReaderLibrary
/usr/share/yacreader/server/docroot -> inside YACReaderLibrary.ini, should I storge it?
```

**Comment by selmf** [comment]
Have a look at our [forum](https://www.yacreader.com/forum/support-linux/658-yacreaderlibraryserver-dockerized). Most issues involving YACReaderLibraryServer and Docker are discussed there and you will find several working docker images.

**Comment by xthursdayx** [comment]
@chinanoahli See also: https://github.com/xthursdayx/yacreaderlibrary-server-docker
