### ISSUE TITLE
Opensuse YAC 9.8.2 cant' open RAR 5 !!!

### ISSUE THREAD

**Issue by MetaStazz** [YACReader/yacreader#307]
It doesn't open rar 5 ??????!!!!!
rar 5 are aournd since 2013.... just saying !!
Those are working in others soft like calibre, okular..etc

As I'm not expert in building stuff, I use the only package I found for opensuse Leap 15.3, the one from the chinese repo
https://build.opensuse.org/package/show/home:opensuse_zh/yacreader

**What could be the benefits of using RAR5 over RAR4?**
* RAR4 was the default RAR format before RAR5. By the introduction of RAR5, the default compression directory size has increased to 1GB in 64 bit systems. For huge files, it’d offer greater compression.
And, be aware that the default size of the RAR compression dictionary was 32MB before RAR5. Now, you can spot the actual difference between these numbers.

* New recovery log is another specialty of RAR5. With a log size equal to or greater than 5% of the file, RAR5 is much more damage resistant than RAR4. It’ll be valid even the file become corrupted.
And, it’s known to have better damaged archive recovery as compared with previous RAR formats. It uses a more advanced file table for quick browsing of archive and it has multicore decompression support too.

* One more important thing is the encryption algorithm RAR5 uses. Unlike its previous version, RAR5 uses a solid 256-bit AES algorithm.

* In many tests, RAR5 outrun 7-zip in terms of its speed and compression ratio although 7-zip is compared to be one of the fastest compression techniques available now.

**Comment by luisangelsm** [comment]
You just need to use the p7zip backend for compressed files. https://github.com/YACReader/yacreader/blob/develop/compressed_archive/README_7zip.txt

**Comment by luisangelsm** [comment]
Windows and macos builds use 7zip, so rar5 is supported by default. In Linux is up to the people maintaining packages and distribution.

**Comment by MetaStazz** [comment]
So.... As I upgrade my system to Leap 15.4, I can't build YAC because I can't install a dependency needed :
`Project ERROR: Could not find poppler-qt5`

**Comment by luisangelsm** [comment]
Use `libpdfium` instead: https://github.com/YACReader/yacreader/blob/develop/dependencies/pdf_backend.pri

**Comment by MetaStazz** [comment]
So.... I had some time to dig in today, and I manage to build it with p7zip and poppler, but when I open a cbr for test it show me an error : 7zip missing !! ??

So... Instead I build it with libarchive from the [Pull](https://github.com/YACReader/yacreader/pull/290) you mentioned !! And everything is working fine so far...
