### ISSUE TITLE
[Feature Idea/Request]

### ISSUE THREAD

**Issue by Gaurav-1306** [YACReader/yacreader#308]
a new user here!
so when I read manga, it has this double manga mode which works for most of the manga. but the issue rises when the cover page is a double-page spread(the page that takes two pages). so if a manga has a double-page spread as the cover page then one of the next two pages generally contains an ad in real manga books. But from where I download they don't give that ad page and hence the way manga double page mode work is disrupted. 
what feature should I be suggesting- a feature when activated, makes that particular page single (like cover page) and then pages after that in double mode only.
Hopefully, I was clear enough. I am new to this coding and open source in general.

**Comment by luisangelsm** [comment]
There is: Options -> Image adjustment -> Show covers as single page (available since 9.7.0)

**Comment by Gaurav-1306** [comment]
> There is: Options -> Image adjustment -> Show covers as single page (available since 9.7.0)

I guess I was unable to explain the problem and feature well. you see I know that covers can be on a single page but as explained above it does not solve all the problems. what I want is that any page can be singled out and pages after that are in double manga mode.
