### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [YACReader/yacreader#31]
i've downloaded Version '9.5.0' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all. i guess the CFBundleVersion and CFShortVersionString entries in your Info.plist file are missing

**Comment by selmf** [comment]
Is this still an issue with 9.6.2?

**Comment by core-code** [comment]
yes. both YACReader and YACReaderLibrary don't have any version numbers.

the CFBundleVersion and CFShortVersionString entries in your Info.plist file are missing

**Comment by selmf** [comment]
I'm not really a OS X guy but sorting out version setting for our build system and CI is currently on my agenda, so I'll look into it. Not sure if there is a straightforward way to do his with our build system though.
Do you happen to have some documentary for Info.plist and the required entries handy?

**Comment by core-code** [comment]
there is some documentation here:
https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

however, i'd recommend comparing the Info.plist with something that Xcode generates for a sample app, as this is like the "best practices".

i think the most important thing is filling out the version numbers, as mentioned, and also importantly removing the 'CFBundleGetInfoString' entry. this one has been deprecated for more than 10 years, and will actually prevent display of the version number in the Finder, even if you do add it.

**Comment by luisangelsm** [comment]
@selmf I will send you the keys you need to set in the Info.plist. I totally forgot about this while I was setting up the azure pipelines.

**Comment by selmf** [comment]
Thanks. If possible I'd like Info.plist to be generated from a template which is configured by our build system instead of having hardcoded version entries.

**Comment by vitorgalvao** [comment]
To add to this, technically you don’t *have to* add the version during the build process, you can add it after it’s done by directly editing the `Info.plist`:

```bash
# Change these values
app_path='/PATH/TO/APP/HERE'
app_version='VERSION NUMBER HERE'

# Keep these as they are
/usr/libexec/PlistBuddy -c "Add :CFBundleVersion string ${app_version}" "${app_path}/Contents/Info.plist"
/usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${app_version}" "${app_path}/Contents/Info.plist"
```

That would use the same version number for both fields. While technically they should be different (e.g. from the latest release, `CFBundleVersion` would be `2106195` and `CFBundleShortVersionString` `9.8.2`), but even having the same version in both fields (or even one of them) would be a major improvement.
