### ISSUE TITLE
[Bug] Editing Jumps

### ISSUE THREAD

**Issue by PlumBlossoms13** [YACReader/yacreader#310]
Hello!
Recently I've noticed that when I edit a manga volume it jumps back to the first volume in the list. It's a bit tedious when the series has a lot of volumes. Thank you!

**Comment by luisangelsm** [comment]
9.9.0.2208262 has an updated editor with new buttons to go to the next/previous comic after you finish editing the current one. When the next comic is loaded the previous on is saved automatically. Save/close buttons close the dialog.

**Comment by luisangelsm** [comment]
9.9.0 is officially out and solves the problem.
