### ISSUE TITLE
9.10.0 fails to compile

### ISSUE THREAD

**Issue by tim77** [YACReader/yacreader#347]
New `9.10.0` fails to compile on Fedora Linux. Previous version used to builds fine.

- [Full build log](https://kojipkgs.fedoraproject.org/work/tasks/41/93590041/build.log)
- [Koij task](https://koji.fedoraproject.org/koji/taskinfo?taskID=93589969)

**Comment by jbeich** [comment]
> /bin/sh: line 1: /usr/lib/qt5/bin/lrelease: No such file or directory

Install `qt5-linguisttools` or similar. See 99114b00e726.

**Comment by luisangelsm** [comment]
@tim77 it compiles in Ubuntu 22.04, which is the version used in CI/CD (Azure Pipelines) to control that compilation doesn't break during development: https://github.com/YACReader/yacreader/blob/develop/azure-pipelines.yml

So probably a problem with dependencies like @jbeich suggested.

**Comment by tim77** [comment]
Indeed, my eyes are swimming. New version [built](https://bodhi.fedoraproject.org/updates/?packages=yacreader) for all branches. Many thanks!
