### ISSUE TITLE
Translations (*.qm) are no longer installed

### ISSUE THREAD

**Issue by jbeich** [YACReader/yacreader#349]
Probably regressed by 99114b00e726

```
$ qmake-qt5
$ make install

$ LANG=de_DE.UTF-8 truss YACReader 2>&1 | fgrep .qm
access("/usr/share/yacreader/languages/yacreader_de_DE.qm",R_OK) ERR#2 'No such file or directory'
access("/usr/share/yacreader/languages/yacreader_de.qm",R_OK) ERR#2 'No such file or directory'
access("/usr/share/yacreader/languages/yacreader_de_de.qm",R_OK) ERR#2 'No such file or directory'
access("/usr/share/yacreader/languages/yacreader_de.qm",R_OK) ERR#2 'No such file or directory'

# Translations are present in build directory
$ find . -name \*.qm
./release/languages/yacreader_de.qm
./release/languages/yacreader_en.qm
./release/languages/yacreader_es.qm
./release/languages/yacreader_fr.qm
./release/languages/yacreader_it.qm
./release/languages/yacreader_nl.qm
./release/languages/yacreader_pt.qm
./release/languages/yacreader_ru.qm
./release/languages/yacreader_tr.qm
./release/languages/yacreader_zh_CN.qm
./release/languages/yacreader_zh_HK.qm
./release/languages/yacreader_zh_TW.qm
./release/languages/yacreaderlibrary_de.qm
./release/languages/yacreaderlibrary_en.qm
./release/languages/yacreaderlibrary_es.qm
./release/languages/yacreaderlibrary_fr.qm
./release/languages/yacreaderlibrary_it.qm
./release/languages/yacreaderlibrary_nl.qm
./release/languages/yacreaderlibrary_pt.qm
./release/languages/yacreaderlibrary_ru.qm
./release/languages/yacreaderlibrary_tr.qm
./release/languages/yacreaderlibrary_zh_CN.qm
./release/languages/yacreaderlibrary_zh_HK.qm
./release/languages/yacreaderlibrary_zh_TW.qm
```

https://github.com/YACReader/yacreader/blob/6cc92a260c954723dd9a1147fca42bdb962b9cdf/YACReader/YACReader.pro#L259-L260

**Comment by luisangelsm** [comment]
The idea behind those changes was to compile the languages at build time instead of having to do it manually, the app has been shipped with stale translation files so many times because of this.

@selmf tested this on linux side, @jbeich what distro are you running?

**Comment by jbeich** [comment]
> @jbeich what distro are you running?

FreeBSD. When preparing [9.9.2 -> 9.10.0 package update](https://github.com/freebsd/freebsd-ports/commit/79d8c4ee48fd) I did confirm UI was no longer translated before filing this issue and applying the workaround.

I maintain some Qt5 packages that embed translations into the binary (e.g., citra-qt and yuzu) but not familar enough with Qt5 to spot why it doesn't work in yacreader case.

**Comment by selmf** [comment]
I can confirm that the language files aren't installed on my Linux box either. I am not sure what is causing this - the languages target is present in the Makefiles and the language files are generated as intended. I'll try to debug it.
