### ISSUE TITLE
Server connectivity QR Code on headless version

### ISSUE THREAD

**Issue by robsonsobral** [YACReader/yacreader#357]
Hi!

Please, is it possible to add the same QRCode of the desktop version to the headless one? Maybe below the libraries list? Is that possible?

Thank you!

**Comment by selmf** [comment]
Hi,
this is on my TODO list but I can't give you any promises as to when I will get around to do it. The code to display a QR code on a terminal is differs from the code to display an image, but it **is** possible.

**Comment by selmf** [comment]
Fixed in YACReader 9.12.0 :)
