### ISSUE TITLE
Unable to disable server after it's been enabled

### ISSUE THREAD

**Issue by rshxyz** [YACReader/yacreader#358]
Hello, 
I am unable to disable the server after it's been enabled

I had to disable it by modifying the ini 
vim .local/share/YACReader/YACReaderLibrary/YACReaderLibrary.ini 
SERVER_ON=true 

version 9.10.0.0 
SYSTEM INFORMATION
Qt version: 5.15.6
Build ABI: x86_64-little_endian-lp64
build CPU architecture: x86_64
CPU architecture: x86_64
Kernel type: linux
Kernel version: 5.15.78-200.fc36.x86_64
Product info: Fedora Linux 36 (Workstation Edition)

GRAPHIC INFORMATION
Screen pixel ratio: 1
OpenGL version: 4.6 desktop

**Comment by selmf** [comment]
I can confirm this issue. In fact, on my system I even get a segfault and YACReaderLibrary crashes.

The problem seems to be that the app tries to refresh the QR code when the server is not running which results in a segfault when trying to access the server port.

**Comment by luisangelsm** [comment]
Fixed here: https://github.com/YACReader/yacreader/commit/35466e5080f48adfd1a9fd95d00fa4049d79945b
