### ISSUE TITLE
Problem with really long comic strips.

### ISSUE THREAD

**Issue by ZeroCool940711** [YACReader/yacreader#363]
Hi there, I recently noticed there is an issue with YacReader when you have an image that is too big, I was reading a manhua called "Nano Machine" and one chapter had only 5 pages but they were pretty long. The first three pages were really long with a resolution up to 800x38748 pixels, YacReader was able to read the first three images but the fourth one was even longer at 800x52518 and it seems like because it was too big YacReader couldn't load it properly which resulted in a "Page not available!" error when trying to read that specific page. When opening the `.cbz` file and extracting the images all of them could be viewed normally on an image viewer like the default Windows Photos app and also ImageGlass but not on YacReader.

**Comment by luisangelsm** [comment]
Could you try the latest dev build please?

**Comment by ZeroCool940711** [comment]
I downloaded the latest artifact from the CI build on the dev build and it seems to work, the image is shown properly, I did multiple tests to make sure and it seems to be fixed on the dev build, not sure if I should close the issue now or wait for the dev build to be on master and then close it.

**Comment by luisangelsm** [comment]
Nice, thanks for testing it, you can close the issue now.
