### ISSUE TITLE
Comic not marked as read in double page mode when odd number of pages

### ISSUE THREAD

**Issue by justThoughtless** [YACReader/yacreader#364]
I use yacreader library to read comics in double page mode when ending of a comic has 2 pages and I go to next comic in series after last page popup. The manga isn't marked as read. When I switch to single page mode for these comics and go to next comic in series then they are marked as read.
![double-page-not-working](https://user-images.githubusercontent.com/46607038/209083350-fe640f0c-f67f-450d-8708-80722c4d96c9.png)
double page - doesn't get marked as read
![single-page-works](https://user-images.githubusercontent.com/46607038/209083385-2a5106ef-ff22-475e-be19-4ca360cd163d.png)
single page - marked as read

**Comment by luisangelsm** [comment]
There is a fix in the latest dev build. Could double check that it works as expected?

**Comment by justThoughtless** [comment]
yeah, working as expected.

Thank You

**Comment by justThoughtless** [comment]
should I close the issue now?

**Comment by luisangelsm** [comment]
I will close it for you.
