### ISSUE TITLE
[Feature Request] Forward/back by single page when in double-page mode

### ISSUE THREAD

**Issue by LunarTulip** [YACReader/yacreader#367]
In double-page mode, currently, one can only deliberately advance two pages at a time, not one page at a time. This occasionally produces issues where spreads get split up, such that the first half of a spread is in one pair-of-displayed-pages and the second half is in the subsequent pair-of-displayed pages.

There is no deep engine-level reason why this has to happen. Indeed, it can already be made to *not* happen given appropriate awkward hacks, such as disabling double-page view, going forward or back one page, and then reenabling it. But I'd like to request that YACReader be updated to *not require* the relevant genre of awkward hacks, by way of the addition of shortcuts which directly implement "go [forward/back] one page", so as to make it easier to get the proper alignment of pages for whichever book one is reading.

(This would be *especially* valuable for those books which repeatedly *change* their spread alignment, e.g. ad-free digital releases of comics which were originally printed with ads in between their chapters and whose alignment ends up, absent those ads, inconsistent. But also useful even for more ordinary books which are consistent in their alignment but whose consistent alignment happens to be out-of-line with how YACReader initially displays them.)

**Comment by luisangelsm** [comment]
This can be done using the "go to page flow", open it, then select the page you want on the left (or right in manga mode).

**Comment by luisangelsm** [comment]
Done here: https://github.com/YACReader/yacreader/commit/f3249e405321ce76df4d550237b18c8d42fcb2e8
