### ISSUE TITLE
Comic View area turns white in Linux

### ISSUE THREAD

**Issue by Vikng412** [YACReader/yacreader#369]
Distro - Fedora 37

 https://imgur.com/a/Ub7nXxs

It's Like this in both Wayland and Xorg

**Comment by luisangelsm** [comment]
Missing dependencies probably. How are you installing YACReader?

That view could also fail if the rendering context can't be initialized, make sure you have the right drivers for you graphics card installed.

**Comment by Vikng412** [comment]
I use the rpm package file from the official download pages. It worked on some installation and after the recent Fedora 38 it started showing white screen again. What are the steps that I can take or a kinda checklist to prevent this from happening in the future?

**Comment by selmf** [comment]
From a quick glance at the dependencies of the Fedora package I'd say this is missing:

qt5-qtquickcontrols2

Which, by the way @luisangelsm, is also missing from the dependency list we have in our installation instructions. Not sure if it is in the changelog.

**Comment by luisangelsm** [comment]
Yes, I didn't update the list in the instructions.

**Comment by Vikng412** [comment]
Thanks a lot for responding.
