### ISSUE TITLE
[Ubuntu, iOS] Connection to library works only when SSH session is running

### ISSUE THREAD

**Issue by bipox** [YACReader/yacreader#370]
**Home server running Ubuntu 22.04
YACReaderLibraryServer installed from repository, no Docker
2 or 3 years old iPad, up to date**

Hi,

YACReader on iOS only is able to connect to my server when there's an SSH session active between another device and my server (SSH running in a terminal, or a connection with SFTP in the file explorer)

How to reproduce:
1) YACReaderLibraryServer running on Ubuntu 22.04
2) on iOS, open YACReader app and try to connect to the YACReader library on the server.
Error message: "Error trying to connect to YACReaderLibrary: 0"
3) connect to the Ubuntu server through SSH from any device
4) immediately iOS YACReader app connects to the library
5) stop all SSH connections
6) after 1-3 seconds, YACReader app can't find the library anymore

**Comment by luisangelsm** [comment]
It looks to me that you are starting the server tied to your user session, so when you exit ssh the server stops.

**Comment by bipox** [comment]
Thanks for your answer. 

It's strange because it worked without issue for a long time.
I don't know how to fix this, so I re-installed YACReader as root and now it stays on.
