### ISSUE TITLE
Allow choosing to default a library to manga mode

### ISSUE THREAD

**Issue by xelivous** [YACReader/yacreader#371]
Right now the sqlite database defaults all comics to non-manga mode, and it doesn't save the setting in the sqlite database upon closing yacreader. Choosing the default to be 1/0 depending on if the library is going to be used for manga or not would be preferable than opening up the sqlite database.

There isn't a simple command to change the default for just a single column in sqlite but most GUIs can do it. Updating the individual manga after importing them can be done with:

```sql
UPDATE comic_info set manga = 1
```

**Comment by luisangelsm** [comment]
Done here: https://github.com/YACReader/yacreader/pull/439

And can be tested in the latest dev build: https://github.com/YACReader/yacreader-dev-builds/releases/tag/9.15.0.2407104
