### ISSUE TITLE
[Feature Request] Add "rescan library for XML" feature to YACReaderLibraryServer

### ISSUE THREAD

**Issue by thedeany** [YACReader/yacreader#376]
Currently there is no way to rescan the library for XML info via the server CLI. Per [our discussion in Discord](https://discord.com/channels/917481792179679263/1015257369409748992/1088212986633670758), I was able to locally mount the network drive on which my comic library sits and use the desktop version of YACReaderLibrary to do the rescan on the "remote" library. However, future users may not have this ability with their network drives or the know-how to do so, so adding the ability to rescan from the server CLI itself would be great!

For example:
```bash
YACReaderLibraryServer rescan-library [library name]
```
or perhaps some sort of flag on `update-library` to rescan the XML and update the library in one command:
```bash
YACReaderLibraryServer update-library [library name] --rescan-xml
```

**Comment by luisangelsm** [comment]
Done.

```
yacreaderlibraryserver rescan-xml-info "C:\xml test import info"
Scanning comics.............Done!
Number of comics processed = 13
```

Also, this: https://github.com/YACReader/yacreader/blob/develop/YACReaderLibraryServer/SETTINGS_README.md

`IMPORT_COMIC_INFO_XML_METADATA=true` can be used to scan xml while adding new comics to the library.
