### ISSUE TITLE
[Feature request] Add an option to adjust or remove completely the inertia when scrolling.

### ISSUE THREAD

**Issue by fuzzfactory0** [YACReader/yacreader#383]
As a touchpad (laptop) user, it's very difficult to control the scrolling of the page, especially on long strip mangas, because of the acceleration and inertia of the scrolling. The page flies by with the slightlest movement, and keeps moving for at least a second after I let go of the touchpad.

It would be very nice if this could be adjusted, so scrolling behaves exactly as it does on a web browser!

**Comment by luisangelsm** [comment]
Done here: https://github.com/YACReader/yacreader/commit/570640777884bc7fb7676a361b93350b2cec2518

![image](https://github.com/YACReader/yacreader/assets/1395876/6b042eab-14ec-4b1a-844b-54e1f4c0bfb2)
