### ISSUE TITLE
[Feature request] Add support for JPEG XL

### ISSUE THREAD

**Issue by Isaacx123** [YACReader/yacreader#385]
I was wondering if it is possible to add support for the JPEG XL image codec.

Thanks.

**Comment by AKL55** [comment]
> 

Download this release https://github.com/nomacs/nomacs/releases/tag/3.17.2282,
Find qjpegxl.dll in the imageformats folder,
And paste on the imageformats folder of yacreader

**Comment by Isaacx123** [comment]
Yeah, it worked on the qt5 build, thanks.
Also added support for AVIF via the same method.

Closing the issue now.
