### ISSUE TITLE
missing translation string

### ISSUE THREAD

**Issue by kofzhanganguo** [YACReader/yacreader#390]
![image](https://github.com/YACReader/yacreader/assets/32073931/634775d6-909b-49e8-92ed-4088460559c7)
The English language pack of the software does not contain these strings, so I have no way to perform localized translations.
![image](https://github.com/YACReader/yacreader/assets/32073931/66cd4c2f-4922-400b-ad3b-7a1ed37f0677)
I opened this English language pack, and I searched for this word, but I couldn’t find this entry, so I couldn’t do localized translation.

**Comment by kofzhanganguo** [comment]
When can the missing strings be updated, the English strings of the software are all missing, and there is no way to perform localized translation.

**Comment by selmf** [comment]
They can be updated whenever a volunteer submits an updated translation.

**Comment by kofzhanganguo** [comment]
Strings are missing from the official English native language pack, and even if I wanted to localize the translation, I couldn't.

**Comment by selmf** [comment]
@luisangelsm you need to run lupdate

**Comment by luisangelsm** [comment]
Updated on develop.
