### ISSUE TITLE
Driver not loaded-Driver not loaded(flatpak 9.13.1)

### ISSUE THREAD

**Issue by Janath1** [YACReader/yacreader#395]
Manjaro Gnome

**Comment by selmf** [comment]
If this happens while trying to open a file and this file is not located in your home directory, you need to manually add permissions. Flatpak should have some guides on how to do this that you can follow.
If this is not related to filesystem access, you need to open an issue here:

[YACReader Flathub](https://github.com/flathub/com.yacreader.YACReader/)

 Please provide proper information on how to reproduce your issue or I will not be able to help you.

**Comment by Janath1** [comment]
i managed to fix it 
it is a permission issue
Thanks buy the way

⁣Get BlueMail for Android ​
