### ISSUE TITLE
Feature Request YACReaderLibrary Server Comics Icon for iPads

### ISSUE THREAD

**Issue by hipco** [YACReader/yacreader#404]
Can you add in a future release the Remote Comics Icon on IPads? Or is there a way to enable it on iPads with the current release?

I'm using iPadOS 17.1.

![iPad](https://github.com/YACReader/yacreader/assets/59048928/1994cc8c-fd26-4ae1-b917-f3491d9e58c4)
![iPhone](https://github.com/YACReader/yacreader/assets/59048928/e1761ed4-52d3-4aff-89d9-9a3728d6b5ca)

**Comment by luisangelsm** [comment]
This repo is for the desktops version only. 

But the feature is there in ipados, you just need to pin the server or the library you want: 
<img width="147" alt="image" src="https://github.com/YACReader/yacreader/assets/1395876/95e0449f-4ebe-45a0-8c27-36334095693c">

Use that pin icon, it is on the right top corner when you browse a server, you can pin a server or a library in a server.
