### ISSUE TITLE
Submit the latest Simplified Chinese language pack

### ISSUE THREAD

**Issue by kofzhanganguo** [YACReader/yacreader#413]
[Simplified Chinese language pack.zip](https://github.com/YACReader/yacreader/files/14076402/Simplified.Chinese.language.pack.zip)

The latest Simplified Chinese language pack for the adapted version YACReader-v9.14.1.2401272, which fixes previous translation errors and completes the translation of all entries.

**Comment by luisangelsm** [comment]
Included here: https://github.com/YACReader/yacreader-dev-builds/releases/tag/9.14.1.2401291

**Comment by luisangelsm** [comment]
Thanks!
