### ISSUE TITLE
Drop date suffix from source files tarball

### ISSUE THREAD

**Issue by tim77** [YACReader/yacreader#421]
Hello. Just a small wish: would be nice to drop date suffix from source files tarball. For example instead of:
```
yacreader-9.14.2.2402143-src.tar.xz
```
use just:
```
yacreader-9.14.2-src.tar.xz
```
Rationale: this could help to automate update process on Linux distros. The quicker update = the happier users! Thanks in advance.

**Comment by luisangelsm** [comment]
that's the build number and a version can have multiple version numbers, maybe i can include a second tarball without it....

**Comment by selmf** [comment]
The main issue is that it is not guessable and it breaks workflows. I also have to manually open the release page and copy the build number for my packages.
For Archlinux, this is negligible, but for other workflows like Debian automatic source import it adds problems.

Ideally, a source tarball should not have a build number. Release tag == version == tarball version

**Comment by luisangelsm** [comment]
done here: https://github.com/YACReader/yacreader/pull/422
