### ISSUE TITLE
Hotkeys for saving

### ISSUE THREAD

**Issue by DeerFee** [YACReader/yacreader#450]
Is it possible to save pages using Ctrl+S?
And can this be done automatically without choosing paths, automatically saving to the folder "%user%\Downloads" (for example)? It would also be nice if the file name could be automatically changed if there's a file with the same name in the directory, meaning if there's "page_1.jpg" it automatically saves the page as "page_1 (1).jpg"

**Comment by luisangelsm** [comment]
Go to the app `Options` (cog in the top right corner) -> `Edit shortcuts` -> `Comics` -> set there the short cut you want to use.

And no, there is no automatic destination folder, thanks for the suggestion, it makes sense if you use the feature a lot.
