### ISSUE TITLE
inconsistent syntax and indenting of the source code

### ISSUE THREAD

**Issue by mytskine** [YACReader/yacreader#48]
The source code is in a bad state. It almost turned me away, but I was interested in learning how to clean up legacy C++ code, so I stuck around. But I'm sure it will discourage potential contributors. 

- The most visible problem is the lack of a consistent indenting: in a single function, it can switch between 2 spaces, 4 spaces and tabs.
- The one-command blocks usually have no braces. It sometimes leads to ambiguous code in sequences like "if if else". But combined with inconsistent indenting, reading the code is a real pain: when several lines are indented like they were inside the block, is it a indentation error or were the braces forgotten?
- There are many small errors that compilers detects (shadowing global vars, .

The pull request  #43 has fixes that remove all the warnings when compiling with g++ 8.3.

Since then, I've used Clang tools to format the source code and enhance the syntax (especially adding braces). It was almost necessary before I could begin adding features. I also fixed the warnings that compiling with Clang detected. I did not create a PR since the prerequisite #43  is still staging, but if you are interested, I could rebase out a few unrelated commits and make this PR. If you want to look at it, my branch is named "clang-tidy" in my fork.

**Comment by luisangelsm** [comment]
Yes I know, sorry for that.

ClangFormat is going to be setup to fix the mess and prevent future inconsistencies.

**Comment by selmf** [comment]
Short update: Were currently playing around with some options and investigating how to implement this as a whole. We will likely go for a route that is similar but not quite the same as your clang-tidy style, @mytskine . Partly because we need some Qt related finetuning and this is a good time to evaluate some of our coding habits, partly because we want a solution that is a little more permanent than just running format on the whole codebase. We also have some code that should not be formatted, so that needs to be taken into account too...

**Comment by mytskine** [comment]
That's great if you can enhance the code base in a way more suitable for the project. My cleanup branch was biased by my own preferences (`clang-format` with webkit style), but you might grab there a few interesting commits that do not relate to code syling.

As an example, here are 2 commit messages that point to bug fixes: "QBoxLayout stretch factors are integers, not floats" and "typeid may return distinct references with same hash_code()". I'm too lazy to redo those patches on an unformatted code and put them into several PR. I also recommend some `clang-tidy` commands. See <https://github.com/mytskine/yacreader/commits/clang-tidy> for all this.

I leave this issue open since the PR #43 that deals with the gcc warnings still applies, and some of the problem come from the bad indentation.

**Comment by selmf** [comment]
OK, I'll keep that in mind. We will likely go for a webkit based style too, with some tweakings for Qt based code and personal preferences. @luisangelsm is still playing with the options. 
The main difference will be setting this up on a per-repo basis and using continuous integration to check landing code for formatting problems.

Once we're finished you can just cherry-pick your fixes and reformat them. You don't need to create a single PR per fix, but keep the size reviewable ;) 

Formatting, of course, is only the first step. YACReader is an old project and it kind of resembles the attic of an old house -  some sections are clean and nicely kept, others dark and dusty, and somewhere in the darkest corners unspoken horrors like @luisangelsm old baby pictures might lurk...

**Comment by luisangelsm** [comment]
Fixed here: https://github.com/YACReader/yacreader/pull/60

**Comment by selmf** [comment]
@luisangelsm you forgot to close the issue ;)
