### ISSUE TITLE
Update 7-zip wrapper

### ISSUE THREAD

**Issue by Monthy** [YACReader/yacreader#52]
Hello, my name is Pedro,
Thanks to your wrapper I managed to use 7-zip in my project, but recently I have managed to update it to use it with the latest versions of the 7-zip sdk as of p7zip ie use the 19.00 and 16.02 respectively, this way you can read files rar5

The project is [Qt7zip](https://github.com/Monthy/Qt7zip) comes with examples and I hope it helps you to update your wrapper and to be able to use the new 7-zip and p7zip libraries, in your wonderful reader comic.

Sorry for my English
***
Hola me llamo Pedro,
Gracias a tu wrapper conseguí usar 7-zip en mi proyecto, pero hace poco he conseguido actualizarlo para usarlo con la ultimas versiones del sdk de 7-zip como de p7zip es decir usar la 19.00 y  16.02 respectivamente, de esta manera ya puede leer archivos rar5.

El proyecto es [Qt7zip](https://github.com/Monthy/Qt7zip) viene con ejemplos y espero que te sirva para poder actualizar tu wrapper y poder usar las nuevas librerías de 7-zip y  p7zip, en tu magnifico lector de cómic.

Un saludo.

**Comment by selmf** [comment]
Thanks for the info! We have an updated 7zip wrapper (18.05 and 16.02, on the develop branch), but we might use your work to upgrade this to 19.00.

For your own project, be careful when using p7zip 16.02. All versions of 7zip that are older than 18.05 have known security vulnerabilities and need to be patched for safe usage. As the p7zip project was abandoned by its author, there won't be any updates for it, but you can get security patches from Linux distributions like Debian.

**Comment by Monthy** [comment]
I had not seen the development version. Anyway, I hope you can update to 19.00
I did not know about the p7zip, I'll look at the patches.
Thank you

**Comment by luisangelsm** [comment]
@Monthy Thanks for letting us know about Qt7zip, keeping 7zip up to date is a nasty chore, it is great to know that Qt7zip is using 19.00, moving from 18.05 to 19.00 is going to be way easier.
