### ISSUE TITLE
YACReader often uses an entire CPU core from launch till exit if hardware acceleration is disabled

### ISSUE THREAD

**Issue by vedgy** [YACReader/yacreader#56]
Steps to reproduce:

0. Disable hardware acceleration in YACReader options.
1. Open a comic book (cbr or cbz). The bug happens more often for large comics (>=100 pages). Also seems to happen more often when opening by double-clicking in YACReaderLibrary. A comic book never opened in YACReader before is preferable.
2. If the YACReader CPU usage goes down to 0-1% after a few seconds, exit YACReader and open the same comic again. This time the CPU usage will likely stay high, e.g. 25% on a 4-CPU-core system.

I tried to debug the issue in Qt Creator by interrupting YACReader built in Debug mode while it was using the entire CPU core. But the call stack didn't indicate a problem in any thread. Tried QML debugging in Qt Creator, but it didn't work on my system for some reason.

System and versions: Manjaro Xfce x64 with latest updates; Qt 5.12.3; https://aur.archlinux.org/packages/yacreader with `CONFIG+=no_pdf` instead of `CONFIG+=pdfium`.

EDIT: the same issue happens when compiling the *develop* branch in Qt Creator using the default *poppler* PDF backend.

**Comment by selmf** [comment]
When you disable the hardware acceleration you enable software rendering for the cover flow. This will naturally use more CPU than hardware rendering, nothing strange about that. This does not affect QML views.

When you open a comic for the first time, YACReader will extract or render its first page. When you open a comic for the second time, it will try to open the last page you viewed, which can need more CPU, depending on the format used.

YACReader will also extract or pre-render the whole comic you opened, starting from the last page you viewed. For some formats, this can generate extra CPU load as some pages are extracted twice (one pass to reach the last page you viewed, second pass to prepare the pages before that page).

And last but not least, YACReader will also create page thumbnails for the cover flow. That also uses CPU and scales with the length of the comic loaded.

The reason for these strategies is to display a page as soon as possible and to buffer the comic for smooth reading. It works very well with files in the 10 to 100 mb range, but with gigabyte size comics it gets a little memory and cpu hungry.

Btw, if you want to see debug output, the develop version of YACReaderLibrary has a command option to set a loglevel on launch. Older versions suffer from a bug where some of our third party code installed a global debug handler which ate all the output without displaying it.

**Comment by vedgy** [comment]
The problem is that the CPU time is unreasonable and I suspect that one CPU core is being used as long as YACReader is open. I opened a 29-page, 11.3 MiB cbr file 19 minutes ago. YACReader was in the background most of this time. The CPU usage is still 25%. GNOME System Monitor indicates that the YACReader process has consumed 19 minutes of CPU time.

I think there are thread safety bugs in *goto_flow.cpp*, which may be responsible for this issue. This class is used only when OpenGL is disabled.

**Comment by vedgy** [comment]
It seems that *goto_flow.cpp* is not at fault even though it probably contains bugs (e.g. neither `SlideInitializer` nor `PageLoader` objects are ever destroyed). In [this branch](https://github.com/vedgy/yacreader/commits/goto_flow-experiments) I eliminated possibly thread-unsafe code from `PageLoader` but the high CPU usage persists.

**Comment by selmf** [comment]
Check pictureflow.cpp and start YACReaderLibrary with --loglevel=debug or even --loglevel=trace. I'm pretty sure you should see some thread related error messages then. Some of the old code uses an antipattern where objects are being moved between threads a lot and if I remember right, the software flow is affected. I created a pr to fix some of these problems last year (#5), but @luisangelsm has yet to review it.

**Comment by luisangelsm** [comment]
I can't replicate this so far.

IIRC both `SlideInitializer` and `PageLoader` are initialized once, so not releasing them won't cause any leaks. The non opengl version of the flow is pretty much abandoned, it is only there as a last resource for people having problems with the opengl implementation.

If you can replicate the issue consistently, and the bug is in YACReader's code, it shouldn't be that hard to find, just look for usages of `QThread` and see if there are any threads running continuosly.

**Comment by vedgy** [comment]
The bug is in YACReader as I can reproduce it consistently without launching YACReaderLibrary now.
When I run YACReader built in Debug mode *without debugging*, I see many repeating errors in the *Application Output* tab of Qt Creator:
```
QObject::killTimer: Timers cannot be stopped from another thread
QObject::startTimer: Timers cannot be started from another thread
```
But these errors appear when YACReader is launched, and then there is only high CPU usage without any new output.
Setting the logging level to Trace in *YACReader/main.cpp* doesn't show any new messages:
```diff
-  logger.setLoggingLevel(QsLogging::InfoLevel);
+  logger.setLoggingLevel(QsLogging::TraceLevel);
```

When I pause the process, there is only one QThread and it is not busy:

> 1 pthread_cond_wait * *GLIBC_2.3.2
2 QWaitCondition::wait(QMutex *, QDeadlineTimer)
3 QWaitCondition::wait(QMutex *, unsigned long)
4 PageLoader::run                                goto_flow.cpp 318
5 ??
6 start_thread
7 clone

In [my experimental branch](https://github.com/vedgy/yacreader/commits/goto_flow-experiments) I eliminated even this QThread, but the high CPU usage remains. The only obvious remaining suspects are the main thread (which is not always at *poll* when paused) and possibly some hidden QML threads (I don't know QML well).

I'll check out *pictureflow.cpp* and #5.

When I enable hardware acceleration, my entire system freezes sometimes (probably because of the buggy Nvidia driver).

**Comment by selmf** [comment]
There is no Qml in the reader. The timer errors are from picture flow, I have seen them a few times during testing but never bothered fixing them. For debugging you can also name the threads (check Q Thread documentation). If I have some time at the weekend I'll try to reproduce this, my machine should be reasonably close to yours (arch Linux, Nvidia)

**Comment by luisangelsm** [comment]
There was bug when using OpenGL (legacy opengl) and Nvidia in Qt causing full usage of a single core, the problem was fixed in YACReader's side stoping rendering when there wasn't nothing new to draw...So high cpu usage was only a problem while animations in the flow were running.

Could you try any other Qt app and see if there are any related problems? It could be a problem between the nvidia driver and some rendering code in Qt.

**Comment by vedgy** [comment]
I have 3 other Qt5 apps constantly running in the background. I bring one of them to the foreground quite often. I remember high CPU usage issues in one of these apps, but they happened very rarely, mostly after waking from hibernation.

I just renamed all YACReader configuration directories and files to rule out a settings corruption or a buggy option. But simply unchecking the hardware acceleration checkbox brought the issue back. I'll try again tomorrow after reboot. Maybe there is some system state corruption. I have noticed this issue before (months ago I think), but it seems to happen much more often today after my debugging.

**Comment by vedgy** [comment]
Neither rebooting nor merging #5 into *develop* made any difference. After disabling hardware acceleration reproducing is simple - neither the Library nor a large file are necessary:
* double-click a comic book in a file manager or launch YACReader from Qt Creator with the full path to a comic book as the command line argument;
* press ESC after the YACReader's CPU usage goes down;
* repeat the previous steps until the CPU usage stays up (usually this happens after 2 or 3 launches).

**Comment by selmf** [comment]
Allright, I was able to reproduce this. For me the behavior described happens after I close YACReader launched by YACReaderLibrary before the comic has finished loading. I have run some tests, but I'm not sure what exactly is happening here.

**Comment by vedgy** [comment]
The bug is clearly in *pictureflow.cpp*. [This commit](https://github.com/vedgy/yacreader/commit/bf16e181c8853f82fa305cdb9c6953474a4aa888) eliminates it, but it also completely breaks the PictureFlow. Now I just have to narrow down the issue and fix it properly.

**Comment by selmf** [comment]
Well, we already knew that the pictureflow code isn't in the best shape. What really bothers me (and @luisangelsm too) is that the cpu bug seemingly only strikes when YACReader is being launched from QtCreator or YACReaderLibrary and the load of the comic was interrupted at least once. Even if we fix the errors in pictureflow exposed by this bug this still does not explain why this is being triggered at all. My gut tells me that there is another problem hiding somewhere, possibly related to our library database backend or the sync mechanism between reader and library, and I *really* don't like that.

Also, if we're going to mess with the pictureflow code, we shouldn't just fix the obvious bugs but do some proper refactoring. That means removing all the dead Qt2 and Qt3 codepaths, properly converting the Qt4 stuff to Qt5, converting the signal/slot connections to [modern syntax](https://wiki.qt.io/New_Signal_Slot_Syntax) to allow our compiler to check for connection errors and preferably getting rid of the whole thread and mutex mess, if possible.

**Comment by vedgy** [comment]
I can easily reproduce the bug by double-clicking in a file manager (i.e. w/o Library). Interrupting the process is also not necessary for me. The bug is not reproducible 100% of the time and its frequency is different on different computers, which suggests it is related to thread safety. The thread safety root cause would also explain experienced differences depending on how the app is launched and whether it was interrupted - it's all about relative timing in different threads.

I no longer advocate the fix I made in #58 because the `PictureFlow` class is clearly not supposed to be shared between threads, and this old code actually helped to discover real thread safety bugs in `GoToFlow`. So I suggest fixing thread safety bugs in `GoToFlow` instead. Please read my comments in #58 and reply there.

**Comment by vedgy** [comment]
By the way, you can merge an updated version of *pictureflow* from upstream if your version of this mini-library has not been customized extensively: [Qt4 cpp](https://doc.qt.io/archives/qt-4.8/qt-demos-embedded-fluidlauncher-pictureflow-cpp.html)+[Qt4 h](https://doc.qt.io/archives/qt-4.8/qt-demos-embedded-fluidlauncher-pictureflow-h.html) or [the author's version](https://github.com/ariya/pictureflow/commits). At least these versions don't support Qt2 and Qt3.

**Comment by selmf** [comment]
Is this still happening?

**Comment by vedgy** [comment]
No, the bug is fixed. I think that I left the issue open to give the maintainers a chance to reply or act on my last comment. Now that I got your attention, I will close the bug and let you create a new issue/task for a *pictureflow* update from upstream, if you think that's worth doing.
