### ISSUE TITLE
Creating and pinning a "roadmap"/"TODO" issue so that we can see what things need worked on

### ISSUE THREAD

**Issue by shimizurei** [YACReader/yacreader#69]
Here's an [example](https://github.com/pirate/ArchiveBox/issues/120).

Also, have you tried the sponsor link? Would that be beneficial, more money to afford you more time to work on YACReader? I dream of using an android version one day...

**Comment by selmf** [comment]
@luisangelsm has a huge list with stuff users requested or he has considered adding, but I don't think it is suitable for publication. Too much old stuff and probably also ideas he does not want to talk about before he's sure they are practicable. I also have my own TODO list, but that is stuff I am working on or am interested in.
But I agree that having a TODO list and/or roadmap would be a good way to make contribution easier.

As for the donations, they are very much appreciated and they do help, but afaik they are nowhere near the amount that would be needed to allow either me or @luisangelsm to work fulltime on YACReader.

**Comment by pirate** [comment]
If it's of any interest, my experience with ArchiveBox is that people appreciate those big lists, even when they have old ideas that might not flesh out, people just love transparency :).  I also recently discovered https://www.codeshelter.co/ which seems to be a great project where people can assist with triage / bugfixing / responding to roadmap questions, maybe it's of use.

(I'm a total spectator without involvement in this project, I just got the notification from the example ticket mentions, so feel free to ignore this comment, I'm sure ya'll have plenty of valid reasons to avoid posting that TODO list.)

**Comment by selmf** [comment]
I'm creating milestones for the next minor and major releases to keep track of issues and features we want to be resolved now, which should help a bit.

For further roadmapping, we are looking into using Github's Projects feature to create a Kanban board, but we will probably evaluate other stuff too.
