### ISSUE TITLE
Crash on edit after get Vine tags (beta 9.5)

### ISSUE THREAD

**Issue by Old-Geek** [YACReader/yacreader#7]
I import Vine tags, i want edit tags and crash.

[crash log.txt](https://github.com/YACReader/yacreader/files/2060003/crash.log.txt)

**Comment by luisangelsm** [comment]
Hi,

I have moved your post n the forum to the apropriate section:
http://www.yacreader.com/forum/testers/1172-yacreader-9-5-0-yacreader-3-0-for-ios?start=10#3957

The bug is already fixed, I'll release a new test version this weekend, the
first beta probably...
