### ISSUE TITLE
YACReader Library quits when right-clicking a file in Grid View on Linux Mint

### ISSUE THREAD

**Issue by yerbestpal** [YACReader/yacreader#70]
I assume this same issue _might_ occur on other Linux distros. When right-clicking any file (I am testing with .cbr files) in YACReader Library while in Grid View, the application quits immediately after. It doesn't occur on the right-click. Instead, it occurs on the next action, which is usually either escaping the right-click menu or selecting an action from it.

**Comment by selmf** [comment]
I think this is a bug we've already encountered on MacOS and that is fixed in #4, but that fix didn't make it into 9.5.0. Could you try building the development branch from source and check if the problem still happens?

**Comment by yerbestpal** [comment]
@selmf the problem seems to have disappeared. All I can think of is that the issue is only present when their is one folder, since I have since added other folders.

**Comment by selmf** [comment]
Closing this issue as the problem can't be reproduced anymore and a fix is in 9.6.0
