### ISSUE TITLE
Build failed 9.6.0 version

### ISSUE THREAD

**Issue by tim77** [YACReader/yacreader#80]
On the make install step:

```
/usr/lib64/qt5/bin/qmake -install qinstall -exe /builddir/build/BUILD/yacreader-9.6.0/YACReader/YACReader /builddir/build/BUILDROOT/yacreader-9.6.0-1.fc30.x86_64/usr/bin/YACReader
cp ../README.txt ../README
cp: cannot stat '../README.txt': No such file or directory
```

Seems like `README.txt` now `README.md`.

**Comment by luisangelsm** [comment]
Good catch, thanks! Looks like having `qmake -install` as a step in CI is necessary to prevent these kind of errors.

BTW `9.6.0` is a prerelease yet.

**Comment by luisangelsm** [comment]
It should be fixed in `develop`.

**Comment by selmf** [comment]
I think it is save to close this bug ;)
