### ISSUE TITLE
CI fails to sign macos builds on PRs from forks

### ISSUE THREAD

**Issue by luisangelsm** [YACReader/yacreader#81]
The solution to this is to disable app code sign on PRs coming from forks.

**Comment by selmf** [comment]
Actually this doesn't only break PRs coming **from** forks, it also breaks CI **on** forks.

**Comment by jeremydouglass** [comment]
Doesn't that make sense? I'm not at all familiar with azure, but if I fork something on github, arbitrarily change it, and then build it, it should be unsigned -- I would think. Otherwise signing doesn't mean anything.

**Comment by luisangelsm** [comment]
prs from forks are already fixed by skipping signing, but signing should also be skipped in forks

**Comment by selmf** [comment]
This is more than just signing not working. Azure treats the whole pipeline as broken because the signature file isn't available. So it doesn't even build on my fork …

**Comment by selmf** [comment]
If I'm not mistaken, @luisangelsm fixed this already.
