### ISSUE TITLE
Support for macOS Catalina (OS X 10.15)

### ISSUE THREAD

**Issue by AbyssLink** [YACReader/yacreader#97]
Please support for macOS Catalina, thanks a lot !
![](https://tva1.sinaimg.cn/large/006y8mN6ly1g8hw8gfmqij30tk0i27a8.jpg)

**Comment by luisangelsm** [comment]
macOS catalina is supported, you just need to let app run, you can do it from the macOS settings...

And yes, I'll add notarization at some point.

**Comment by ShiroCheng** [comment]
> macOS catalina is supported, you just need to let app run, you can do it from the macOS settings...
> 
> And yes, I'll add notarization at some point.

OK, thank you for your reply, also waiting for the notarization one day.😆
